bup.in: move variable creation in EXEC section for better readability
This make the CHECK CONFIG section stand out more, and also brings
variables that are constructed with configuration closer to where they
are used.

It's also more sane that way since once we start building those
variables we've completed sanity checking.

diff --git a/handlers/bup.in b/handlers/bup.in
--- a/handlers/bup.in
+++ b/handlers/bup.in
@@ -64,53 +64,9 @@ getconf remote_bupdir
 getconf host localhost
 getconf user
 
-SAVEIFS=$IFS
-IFS=$(echo -en "\n\b")
-# TODO: order the includes and excludes
-# includes
-PATH_LIST=
-for i in $path; do
-   PATH_LIST="${PATH_LIST}'${i}' " ;;
-done
-# excludes
-EXCLUDE_LIST=
-for i in $exclude; do
-   EXCLUDE_LIST="${EXCLUDE_LIST}--exclude '${i}' " ;;
-done
-# excludes with regexp
-EXCLUDE_RX_LIST=
-for i in $exclude_rx; do
-   EXCLUDE_RX_LIST="${EXCLUDE_RX_LIST}--exclude-rx '${i}' " ;;
-done
-
-IFS=$SAVEIFS
-
-debug "backup type is set to '$desttype'"
-
-[ -n "$test" ] || test=0
-
-REMOTE_URL=
-if [ "$desttype" != "local" ]; then
-   if [ "$testconnect" = "yes" ] || [ "${test}" -eq 1 ]; then
-      ssh_test_connection $user $host
-   fi
-
-   REMOTE_URL="-r $user@$host:$remote_bupdir"
-
-   if [ "${test}" -eq 0 ]; then
-      # Even though we're already doing this in bup.helper, this gives users the
-      # possibility to just move the bup repository out of the way in case of
-      # corruption and let the next backup run automatically create a new repository.
-      #
-      # calling bup init on an already existing repository is safe.
-      debug "Initializing remote bupdir if it does not exist"
-      output=`ssh $user@$host "mkdir -p $remote_bupdir && bup -d '$remote_bupdir' init"`
-      if [ "$?" != "0" ]; then
-         fatal "An error occurred during repository initialization: $output"
-      fi
-   fi
-fi
-
+# We need to export this before verifying bup's version in the CHECK CONFIG
+# section since we're calling bup and it will bug us about the default ~/.bup
+# location if it doesn't know where its repository is placed.
 if [ -n "$bupdir" ]; then
    BUP_DIR="$bupdir"
    export BUP_DIR
@@ -118,6 +74,10 @@ if [ -n "$bupdir" ]; then
 fi
 
 ### CHECK CONFIG ###
+debug "backup type is set to '$desttype'"
+
+[ -n "$test" ] || test=0
+
 if [ -z "$path" ]; then
    fatal "No source path was given."
 fi
@@ -150,6 +110,48 @@ fi
 # This is not yet implemented in bup itself.
 
 ### EXECUTE ###
+SAVEIFS=$IFS
+IFS=$(echo -en "\n\b")
+# TODO: order the includes and excludes
+# includes
+PATH_LIST=
+for i in $path; do
+   PATH_LIST="${PATH_LIST}'${i}' " ;;
+done
+# excludes
+EXCLUDE_LIST=
+for i in $exclude; do
+   EXCLUDE_LIST="${EXCLUDE_LIST}--exclude '${i}' " ;;
+done
+# excludes with regexp
+EXCLUDE_RX_LIST=
+for i in $exclude_rx; do
+   EXCLUDE_RX_LIST="${EXCLUDE_RX_LIST}--exclude-rx '${i}' " ;;
+done
+IFS=$SAVEIFS
+
+REMOTE_URL=
+if [ "$desttype" != "local" ]; then
+   if [ "$testconnect" = "yes" ] || [ "${test}" -eq 1 ]; then
+      ssh_test_connection $user $host
+   fi
+
+   REMOTE_URL="-r $user@$host:$remote_bupdir"
+
+   if [ "${test}" -eq 0 ]; then
+      # Even though we're already doing this in bup.helper, this gives users the
+      # possibility to just move the bup repository out of the way in case of
+      # corruption and let the next backup run automatically create a new
+      # repository.
+      #
+      # calling bup init on an already existing repository is safe.
+      debug "Initializing remote bupdir if it does not exist"
+      output=`ssh $user@$host "mkdir -p $remote_bupdir && bup -d '$remote_bupdir' init"`
+      if [ "$?" != "0" ]; then
+         fatal "An error occurred during repository initialization: $output"
+      fi
+   fi
+fi
 
 if [ "${test}" -eq 0 ]; then
    if [ "$desttype" = "on" ]; then
