dup: now forbid to (try to) backup /

diff --git a/handlers/dup b/handlers/dup
--- a/handlers/dup
+++ b/handlers/dup
@@ -144,6 +144,7 @@ done
 	
 # includes 
 for i in $include; do
+   [ "$i" != "/" ] || fatal "Sorry, you cannot use 'include = /'"
    str="${i//__star__/*}"
    str=`readlink -f $str`
    if [ -n "$str" ]; then
