Make all indentation consistent.
Previously, there were many indentation styles in use: Real tabs, 2, 3
or 4 spaces, mixing these within the same file, function or even within
a single line.

This commit changes all bash scripts in the handlers, src and lib dirs
to use consistent indentation: three spaces are now used everywhere.
Other files (e.g. Makefiles) are left untouched.

Additionally, this commit removes all trailing whitespace.

diff --git a/handlers/dup.in b/handlers/dup.in
--- a/handlers/dup.in
+++ b/handlers/dup.in
@@ -66,9 +66,9 @@ if [ "$testconnect" == "yes" ]; then
       if [ ! $test ]; then
          result=`ssh $sshoptions -o PasswordAuthentication=no $desthost -l $destuser 'echo -n 1'`
          if [ "$result" != "1" ]; then
-	    fatal "Can't connect to $desthost as $destuser."
+            fatal "Can't connect to $desthost as $destuser."
          else
-	    debug "Connected to $desthost as $destuser successfully"
+            debug "Connected to $desthost as $destuser successfully"
          fi
       fi
    fi
@@ -152,7 +152,7 @@ fi
 # If incremental==no, force a full backup anyway.
 if [ "$incremental" == "no" ]; then
    # before 0.4.4, full was an option and not a command
-   if [ "$duplicity_major" -le 0 -a "$duplicity_minor" -le 4 -a "$duplicity_sub" -lt 4 ]; then   
+   if [ "$duplicity_major" -le 0 -a "$duplicity_minor" -le 4 -a "$duplicity_sub" -lt 4 ]; then
       execstr_options="${execstr_options} --full"
    else
       execstr_command="full"
@@ -204,9 +204,9 @@ done
 if [ $usevserver = yes ]; then
    for vserver in $vsnames; do
       for vi in $vsinclude; do
-	 str="${vi//__star__/*}"
-	 str="$VROOTDIR/$vserver$str"
-	 execstr_source="${execstr_source} --include '$str'"
+         str="${vi//__star__/*}"
+         str="$VROOTDIR/$vserver$str"
+         execstr_source="${execstr_source} --include '$str'"
       done
    done
 fi
@@ -229,11 +229,11 @@ if [ "$duplicity_major" -ge 0 -a "$duplicity_minor" -ge 4 -a "$duplicity_sub" -g
          "$precmd duplicity cleanup --force $execstr_options $execstr_serverpart 2>&1"`
       exit_code=$?
       if [ $exit_code -eq 0 ]; then
-	 debug $output
-	 info "Duplicity cleanup finished successfully."
+         debug $output
+         info "Duplicity cleanup finished successfully."
       else
-	 debug $output
-	 warning "Duplicity cleanup failed."
+         debug $output
+         warning "Duplicity cleanup failed."
       fi
    fi
 fi
@@ -244,17 +244,17 @@ if [ "$keep" != "yes" ]; then
       debug "$precmd duplicity remove-older-than $keep --force $execstr_options $execstr_serverpart"
       if [ ! $test ]; then
          export PASSPHRASE=$password
-	 output=`nice -n $nicelevel \
+         output=`nice -n $nicelevel \
                    su -c \
                       "$precmd duplicity remove-older-than $keep --force $execstr_options $execstr_serverpart 2>&1"`
-	 exit_code=$?
-	 if [ $exit_code -eq 0 ]; then
-	    debug $output
-	    info "Duplicity remove-older-than finished successfully."
-	 else
-	    debug $output
-	    warning "Duplicity remove-older-than failed."
-	 fi
+         exit_code=$?
+         if [ $exit_code -eq 0 ]; then
+            debug $output
+            info "Duplicity remove-older-than finished successfully."
+         else
+            debug $output
+            warning "Duplicity remove-older-than failed."
+         fi
       fi
    fi
 fi
diff --git a/handlers/maildir.in b/handlers/maildir.in
--- a/handlers/maildir.in
+++ b/handlers/maildir.in
@@ -6,17 +6,17 @@
 #  to a remote server. It is designed to be run with low overhead
 #  in terms of cpu and bandwidth so it runs pretty slow.
 #  Hardlinking is used to save storage space.
-# 
+#
 #  This handler expects that your maildir directory structure is
 #  either one of the following:
-# 
-#  1. /$srcdir/[a-zA-Z0-9]/$user for example: 
+#
+#  1. /$srcdir/[a-zA-Z0-9]/$user for example:
 #  /var/maildir/a/anarchist
 #  /var/maildir/a/arthur
 #  ...
 #  /var/maildir/Z/Zaphod
 #  /var/maildir/Z/Zebra
-#  
+#
 #  2. or the following:
 #  /var/maildir/domain.org/user1
 #  /var/maildir/domain.org/user2
@@ -25,7 +25,7 @@
 #  /var/maildir/anotherdomain.org/user2
 #  ...
 #
-#  if the configuration is setup to have keepdaily at 3, 
+#  if the configuration is setup to have keepdaily at 3,
 #  keepweekly is 2, and keepmonthly is 1, then each user's
 #  maildir backup snapshot directory will contain these files:
 #    daily.1
@@ -41,15 +41,15 @@
 #  We handle each maildir individually because it becomes very
 #  unweldy to hardlink and rsync many hundreds of thousands
 #  of files at once. It is much faster to take on smaller
-#  chunks at a time. 
+#  chunks at a time.
 #
-#  For the backup rotation to work, destuser must be able to run 
+#  For the backup rotation to work, destuser must be able to run
 #  arbitrary bash commands on the desthost.
 #
 #  Any maildir which is deleted from the source will be moved to
-#  "deleted" directory in the destination. It is up to you to 
+#  "deleted" directory in the destination. It is up to you to
 #  periodically remove this directory or old maildirs in it.
-# 
+#
 ##############################################################
 
 getconf rotate yes
@@ -91,33 +91,33 @@ excludes="--exclude '.Trash/\*' --exclude '.Mistakes/\*' --exclude '.Spam/\*'"
 ### FUNCTIONS
 
 function do_user() {
-	local user=$1
-	local btype=$2
-        local userdir=${3%/}
-        local source="$srcdir/$userdir/$user/"
-        local target="$destdir/$userdir/$user/$btype.1"
-	if [ ! -d $source ]; then
-	  warning "maildir $source not found"
-	  return
-    fi
+   local user=$1
+   local btype=$2
+   local userdir=${3%/}
+   local source="$srcdir/$userdir/$user/"
+   local target="$destdir/$userdir/$user/$btype.1"
+   if [ ! -d $source ]; then
+      warning "maildir $source not found"
+      return
+   fi
 
-	debug "syncing"
-	ret=`$RSYNC -e "ssh -p $destport -i $destid_file" -r \
-		--links --ignore-existing --delete --size-only --bwlimit=$speedlimit \
-		--exclude '.Trash/*' --exclude '.Mistakes/*' --exclude '.Spam/*' \
-		$source $destuser@$desthost:$target \
-		2>&1`
-	ret=$?
-	# ignore 0 (success) and 24 (file vanished before it could be copied)
-	if [ $ret != 0 -a $ret != 24 ]; then
-		warning "rsync $user failed"
-		warning "  returned: $ret"
-		let "failedcount = failedcount + 1"
-		if [ $failedcount -gt 100 ]; then
-			fatal "100 rsync errors -- something is not working right. bailing out."
-		fi
-	fi
-	ssh -o PasswordAuthentication=no $desthost -l $destuser -i $destid_file "date +%c%n%s > $target/created"
+   debug "syncing"
+   ret=`$RSYNC -e "ssh -p $destport -i $destid_file" -r \
+      --links --ignore-existing --delete --size-only --bwlimit=$speedlimit \
+      --exclude '.Trash/*' --exclude '.Mistakes/*' --exclude '.Spam/*' \
+      $source $destuser@$desthost:$target \
+      2>&1`
+   ret=$?
+   # ignore 0 (success) and 24 (file vanished before it could be copied)
+   if [ $ret != 0 -a $ret != 24 ]; then
+      warning "rsync $user failed"
+      warning "  returned: $ret"
+      let "failedcount = failedcount + 1"
+      if [ $failedcount -gt 100 ]; then
+         fatal "100 rsync errors -- something is not working right. bailing out."
+      fi
+   fi
+   ssh -o PasswordAuthentication=no $desthost -l $destuser -i $destid_file "date +%c%n%s > $target/created"
 }
 
 # remove any maildirs from backup which might have been deleted
@@ -125,116 +125,116 @@ function do_user() {
 # (actually, it just moved them to the directory "deleted")
 
 function do_remove() {
-	local tmp1=`maketemp maildir-tmp-file`
-	local tmp2=`maketemp maildir-tmp-file`
-	
-	ssh -p $destport -i $destid_file $destuser@$desthost mkdir -p "$destdir/deleted"
-        cd "$srcdir" 
-        for userdir in `ls -d1 */`; do
-           ls -1 "$srcdir/$userdir" | sort > $tmp1
-           ssh -p $destport -i $destid_file $destuser@$desthost ls -1 "$destdir/$userdir" | sort > $tmp2
-		for deluser in `join -v 2 $tmp1 $tmp2`; do
-			[ "$deluser" != "" ] || continue
-                        info "removing $destuser@$desthost:$destdir/$userdir$deluser/"
-                        ssh -p $destport -i $destid_file $destuser@$desthost mv "$destdir/$userdir$deluser/" "$destdir/deleted"
-			ssh -p $destport -i $destid_file $destuser@$desthost "date +%c%n%s > '$destdir/deleted/$deluser/deleted_on'"
-		done
-	done
-	rm $tmp1
-	rm $tmp2
+   local tmp1=`maketemp maildir-tmp-file`
+   local tmp2=`maketemp maildir-tmp-file`
+
+   ssh -p $destport -i $destid_file $destuser@$desthost mkdir -p "$destdir/deleted"
+      cd "$srcdir"
+      for userdir in `ls -d1 */`; do
+         ls -1 "$srcdir/$userdir" | sort > $tmp1
+         ssh -p $destport -i $destid_file $destuser@$desthost ls -1 "$destdir/$userdir" | sort > $tmp2
+      for deluser in `join -v 2 $tmp1 $tmp2`; do
+         [ "$deluser" != "" ] || continue
+         info "removing $destuser@$desthost:$destdir/$userdir$deluser/"
+         ssh -p $destport -i $destid_file $destuser@$desthost mv "$destdir/$userdir$deluser/" "$destdir/deleted"
+         ssh -p $destport -i $destid_file $destuser@$desthost "date +%c%n%s > '$destdir/deleted/$deluser/deleted_on'"
+      done
+   done
+   rm $tmp1
+   rm $tmp2
 }
 
 function do_rotate() {
-	[ "$rotate" == "yes" ] || return;
-	local user=$1
-        local userdir=${2%/}
-        local backuproot="$destdir/$userdir/$user"
+   [ "$rotate" == "yes" ] || return;
+   local user=$1
+   local userdir=${2%/}
+   local backuproot="$destdir/$userdir/$user"
 (
-	ssh -T -o PasswordAuthentication=no $desthost -l $destuser -i $destid_file <<EOF
+   ssh -T -o PasswordAuthentication=no $desthost -l $destuser -i $destid_file <<EOF
 ##### BEGIN REMOTE SCRIPT #####
-	seconds_daily=86400
-	seconds_weekly=604800
-	seconds_monthly=2628000
-	keepdaily=$keepdaily
-	keepweekly=$keepweekly
-	keepmonthly=$keepmonthly
-	now=\`date +%s\`
+   seconds_daily=86400
+   seconds_weekly=604800
+   seconds_monthly=2628000
+   keepdaily=$keepdaily
+   keepweekly=$keepweekly
+   keepmonthly=$keepmonthly
+   now=\`date +%s\`
 
-	if [ ! -d "$backuproot" ]; then
-		echo "Debug: skipping rotate of $user. $backuproot doesn't exist."
-		exit
-	fi
-	for rottype in daily weekly monthly; do
-		seconds=\$((seconds_\${rottype}))
+   if [ ! -d "$backuproot" ]; then
+      echo "Debug: skipping rotate of $user. $backuproot doesn't exist."
+      exit
+   fi
+   for rottype in daily weekly monthly; do
+      seconds=\$((seconds_\${rottype}))
 
-		dir="$backuproot/\$rottype"
-		if [ ! -d \$dir.1 ]; then
-			echo "Debug: \$dir.1 does not exist, skipping."
-			continue 1
-		elif [ ! -f \$dir.1/created ]; then
-			echo "Warning: \$dir.1/created does not exist. This backup may be only partially completed. Skipping rotation."
-			continue 1
-		fi
-		
-		# Rotate the current list of backups, if we can.
-		oldest=\`find $backuproot -maxdepth 1 -type d -name \$rottype'.*' | @SED@ 's/^.*\.//' | sort -n | tail -1\`
-		#echo "Debug: oldest \$oldest"
-		[ "\$oldest" == "" ] && oldest=0
-		for (( i=\$oldest; i > 0; i-- )); do
-			if [ -d \$dir.\$i ]; then
-				if [ -f \$dir.\$i/created ]; then
-					created=\`tail -1 \$dir.\$i/created\`
-				else
-					created=0
-				fi
-				cutoff_time=\$(( now - (seconds*(i-1)) ))
-				if [ ! \$created -gt \$cutoff_time ]; then
-					next=\$(( i + 1 ))
-					if [ ! -d \$dir.\$next ]; then
-						echo "Debug: \$rottype.\$i --> \$rottype.\$next"
-						mv \$dir.\$i \$dir.\$next
-						date +%c%n%s > \$dir.\$next/rotated
-					else
-						echo "Debug: skipping rotation of \$dir.\$i because \$dir.\$next already exists."
-					fi
-				else
-					echo "Debug: skipping rotation of \$dir.\$i because it was created" \$(( (now-created)/86400)) "days ago ("\$(( (now-cutoff_time)/86400))" needed)."
-				fi
-			fi
-		done
-	done
+      dir="$backuproot/\$rottype"
+      if [ ! -d \$dir.1 ]; then
+         echo "Debug: \$dir.1 does not exist, skipping."
+         continue 1
+      elif [ ! -f \$dir.1/created ]; then
+         echo "Warning: \$dir.1/created does not exist. This backup may be only partially completed. Skipping rotation."
+         continue 1
+      fi
 
-	max=\$((keepdaily+1))
-	if [ \( \$keepweekly -gt 0 -a -d $backuproot/daily.\$max \) -a ! -d $backuproot/weekly.1 ]; then
-		echo "Debug: daily.\$max --> weekly.1"
-		mv $backuproot/daily.\$max $backuproot/weekly.1
-		date +%c%n%s > $backuproot/weekly.1/rotated
-	fi
+      # Rotate the current list of backups, if we can.
+      oldest=\`find $backuproot -maxdepth 1 -type d -name \$rottype'.*' | @SED@ 's/^.*\.//' | sort -n | tail -1\`
+      #echo "Debug: oldest \$oldest"
+      [ "\$oldest" == "" ] && oldest=0
+      for (( i=\$oldest; i > 0; i-- )); do
+         if [ -d \$dir.\$i ]; then
+            if [ -f \$dir.\$i/created ]; then
+               created=\`tail -1 \$dir.\$i/created\`
+            else
+               created=0
+            fi
+            cutoff_time=\$(( now - (seconds*(i-1)) ))
+            if [ ! \$created -gt \$cutoff_time ]; then
+               next=\$(( i + 1 ))
+               if [ ! -d \$dir.\$next ]; then
+                  echo "Debug: \$rottype.\$i --> \$rottype.\$next"
+                  mv \$dir.\$i \$dir.\$next
+                  date +%c%n%s > \$dir.\$next/rotated
+               else
+                  echo "Debug: skipping rotation of \$dir.\$i because \$dir.\$next already exists."
+               fi
+            else
+               echo "Debug: skipping rotation of \$dir.\$i because it was created" \$(( (now-created)/86400)) "days ago ("\$(( (now-cutoff_time)/86400))" needed)."
+            fi
+         fi
+      done
+   done
 
-	max=\$((keepweekly+1))
-	if [ \( \$keepmonthly -gt 0 -a -d $backuproot/weekly.\$max \) -a ! -d $backuproot/monthly.1 ]; then
-		echo "Debug: weekly.\$max --> monthly.1"
-		mv $backuproot/weekly.\$max $backuproot/monthly.1
-		date +%c%n%s > $backuproot/monthly.1/rotated
-	fi
+   max=\$((keepdaily+1))
+   if [ \( \$keepweekly -gt 0 -a -d $backuproot/daily.\$max \) -a ! -d $backuproot/weekly.1 ]; then
+      echo "Debug: daily.\$max --> weekly.1"
+      mv $backuproot/daily.\$max $backuproot/weekly.1
+      date +%c%n%s > $backuproot/weekly.1/rotated
+   fi
 
-	for rottype in daily weekly monthly; do
-		max=\$((keep\${rottype}+1))
-		dir="$backuproot/\$rottype"
-		oldest=\`find $backuproot -maxdepth 1 -type d -name \$rottype'.*' | @SED@ 's/^.*\.//' | sort -n | tail -1\`
-		[ "\$oldest" == "" ] && oldest=0 
-		# if we've rotated the last backup off the stack, remove it.
-		for (( i=\$oldest; i >= \$max; i-- )); do
-			if [ -d \$dir.\$i ]; then
-				if [ -d $backuproot/rotate.tmp ]; then
-					echo "Debug: removing rotate.tmp"
-					rm -rf $backuproot/rotate.tmp
-				fi
-				echo "Debug: moving \$rottype.\$i to rotate.tmp"
-				mv \$dir.\$i $backuproot/rotate.tmp
-			fi
-		done
-	done
+   max=\$((keepweekly+1))
+   if [ \( \$keepmonthly -gt 0 -a -d $backuproot/weekly.\$max \) -a ! -d $backuproot/monthly.1 ]; then
+      echo "Debug: weekly.\$max --> monthly.1"
+      mv $backuproot/weekly.\$max $backuproot/monthly.1
+      date +%c%n%s > $backuproot/monthly.1/rotated
+   fi
+
+   for rottype in daily weekly monthly; do
+      max=\$((keep\${rottype}+1))
+      dir="$backuproot/\$rottype"
+      oldest=\`find $backuproot -maxdepth 1 -type d -name \$rottype'.*' | @SED@ 's/^.*\.//' | sort -n | tail -1\`
+      [ "\$oldest" == "" ] && oldest=0
+      # if we've rotated the last backup off the stack, remove it.
+      for (( i=\$oldest; i >= \$max; i-- )); do
+         if [ -d \$dir.\$i ]; then
+            if [ -d $backuproot/rotate.tmp ]; then
+               echo "Debug: removing rotate.tmp"
+               rm -rf $backuproot/rotate.tmp
+            fi
+            echo "Debug: moving \$rottype.\$i to rotate.tmp"
+            mv \$dir.\$i $backuproot/rotate.tmp
+         fi
+      done
+   done
 ####### END REMOTE SCRIPT #######
 EOF
 ) | (while read a; do passthru $a; done)
@@ -243,67 +243,67 @@ EOF
 
 
 function setup_remote_dirs() {
-	local user=$1
-	local backuptype=$2
-        local userdir=${3%/}
-        local dir="$destdir/$userdir/$user/$backuptype"
-        local tmpdir="$destdir/$userdir/$user/rotate.tmp"
+   local user=$1
+   local backuptype=$2
+   local userdir=${3%/}
+   local dir="$destdir/$userdir/$user/$backuptype"
+   local tmpdir="$destdir/$userdir/$user/rotate.tmp"
 (
-	ssh -T -o PasswordAuthentication=no $desthost -l $destuser -i $destid_file <<EOF
-		if [ ! -d $destdir ]; then
-			echo "Fatal: Destination directory $destdir does not exist on host $desthost."
-			exit 1
-		elif [ -d $dir.1 ]; then
-			if [ -f $dir.1/created ]; then
-				echo "Warning: $dir.1 already exists. Overwriting contents."
-			else
-				echo "Warning: we seem to be resuming a partially written $dir.1"
-			fi
-		else
-			if [ -d $tmpdir ]; then
-				mv $tmpdir $dir.1
-				if [ \$? == 1 ]; then
-					echo "Fatal: could mv $destdir/rotate.tmp $dir.1 on host $desthost"
-					exit 1
-				fi
-			else
-				mkdir --parents $dir.1
-				if [ \$? == 1 ]; then
-					echo "Fatal: could not create directory $dir.1 on host $desthost"
-					exit 1
-				fi
-			fi
-			if [ -d $dir.2 ]; then
-				echo "Debug: update links $backuptype.2 --> $backuptype.1"
-				cp -alf $dir.2/. $dir.1
-				#if [ \$? == 1 ]; then
-				#	echo "Fatal: could not create hard links to $dir.1 on host $desthost"
-				#	exit 1
-				#fi
-			fi
-		fi
-		[ -f $dir.1/created ] && rm $dir.1/created
-		[ -f $dir.1/rotated ] && rm $dir.1/rotated
-		exit 0
+   ssh -T -o PasswordAuthentication=no $desthost -l $destuser -i $destid_file <<EOF
+      if [ ! -d $destdir ]; then
+         echo "Fatal: Destination directory $destdir does not exist on host $desthost."
+         exit 1
+      elif [ -d $dir.1 ]; then
+         if [ -f $dir.1/created ]; then
+            echo "Warning: $dir.1 already exists. Overwriting contents."
+         else
+            echo "Warning: we seem to be resuming a partially written $dir.1"
+         fi
+      else
+         if [ -d $tmpdir ]; then
+            mv $tmpdir $dir.1
+            if [ \$? == 1 ]; then
+               echo "Fatal: could mv $destdir/rotate.tmp $dir.1 on host $desthost"
+               exit 1
+            fi
+         else
+            mkdir --parents $dir.1
+            if [ \$? == 1 ]; then
+               echo "Fatal: could not create directory $dir.1 on host $desthost"
+               exit 1
+            fi
+         fi
+         if [ -d $dir.2 ]; then
+            echo "Debug: update links $backuptype.2 --> $backuptype.1"
+            cp -alf $dir.2/. $dir.1
+            #if [ \$? == 1 ]; then
+            #   echo "Fatal: could not create hard links to $dir.1 on host $desthost"
+            #   exit 1
+            #fi
+         fi
+      fi
+      [ -f $dir.1/created ] && rm $dir.1/created
+      [ -f $dir.1/rotated ] && rm $dir.1/rotated
+      exit 0
 EOF
 ) | (while read a; do passthru $a; done)
 
-	if [ $? == 1 ]; then exit; fi
+   if [ $? == 1 ]; then exit; fi
 }
 
 function start_mux() {
-	if [ "$multiconnection" == "yes" ]; then
-		debug "Starting dummy ssh connection"
-		ssh -p $destport -i $destid_file $destuser@$desthost sleep 1d &
-        sleep 1
-	fi
+   if [ "$multiconnection" == "yes" ]; then
+      debug "Starting dummy ssh connection"
+      ssh -p $destport -i $destid_file $destuser@$desthost sleep 1d &
+      sleep 1
+   fi
 }
 
 function end_mux() {
-	if [ "$multiconnection" == "yes" ]; then
-		debug "Stopping dummy ssh connection"
-		ssh -p $destport -i $destid_file $destuser@$desthost pkill sleep
-	fi
+   if [ "$multiconnection" == "yes" ]; then
+      debug "Stopping dummy ssh connection"
+      ssh -p $destport -i $destid_file $destuser@$desthost pkill sleep
+   fi
 }
 
 ###
@@ -312,10 +312,10 @@ function end_mux() {
 # see if we can login
 debug "ssh -o PasswordAuthentication=no $desthost -l $destuser -i $destid_file 'echo -n 1'"
 if [ ! $test ]; then
-	result=`ssh -o PasswordAuthentication=no $desthost -l $destuser -i $destid_file 'echo -n 1' 2>&1`
-	if [ "$result" != "1" ]; then
-		fatal "Can't connect to $desthost as $destuser using $destid_file."
-	fi
+   result=`ssh -o PasswordAuthentication=no $desthost -l $destuser -i $destid_file 'echo -n 1' 2>&1`
+   if [ "$result" != "1" ]; then
+      fatal "Can't connect to $desthost as $destuser using $destid_file."
+   fi
 fi
 
 end_mux
@@ -324,47 +324,46 @@ start_mux
 ## SANITY CHECKS ##
 status=`ssh -p $destport -i $destid_file $destuser@$desthost "[ -d \"$destdir\" ] && echo 'ok'"`
 if [ "$status" != "ok" ]; then
-	end_mux
-	fatal "Destination directory $destdir doesn't exist!"
-    exit
+   end_mux
+   fatal "Destination directory $destdir doesn't exist!"
+   exit
 fi
 
 ### REMOVE OLD MAILDIRS ###
 
 if [ "$remove" == "yes" ]; then
-	do_remove
+   do_remove
 fi
 
 ### MAKE BACKUPS ###
 
 if [ "$backup" == "yes" ]; then
-	if [ $keepdaily -gt 0 ]; then btype=daily
-	elif [ $keepweekly -gt 0 ]; then btype=weekly
-	elif [ $keepmonthly -gt 0 ]; then btype=monthly
-	else fatal "keeping no backups"; fi
-	
-	if [ "$testuser" != "" ]; then
-		cd "$srcdir/${user:0:1}"
-		do_rotate $testuser
-		setup_remote_dirs $testuser $btype
-		do_user $testuser $btype
-	else
-                [ -d "$srcdir" ] || fatal "directory $srcdir not found."
-                cd "$srcdir"
-                for userdir in `ls -d1 */`; do
-                   [ -d "$srcdir/$userdir" ] || fatal "directory $srcdir/$userdir not found."
-                   cd "$srcdir/$userdir"
-                   debug $userdir
-			for user in `ls -1`; do
-				[ "$user" != "" ] || continue
-                                debug "$user $userdir"
-                                do_rotate $user $userdir
-                                setup_remote_dirs $user $btype $userdir
-                                do_user $user $btype $userdir
-			done
-		done
-	fi
+   if [ $keepdaily -gt 0 ]; then btype=daily
+   elif [ $keepweekly -gt 0 ]; then btype=weekly
+   elif [ $keepmonthly -gt 0 ]; then btype=monthly
+   else fatal "keeping no backups"; fi
+
+   if [ "$testuser" != "" ]; then
+      cd "$srcdir/${user:0:1}"
+      do_rotate $testuser
+      setup_remote_dirs $testuser $btype
+      do_user $testuser $btype
+   else
+      [ -d "$srcdir" ] || fatal "directory $srcdir not found."
+      cd "$srcdir"
+      for userdir in `ls -d1 */`; do
+         [ -d "$srcdir/$userdir" ] || fatal "directory $srcdir/$userdir not found."
+         cd "$srcdir/$userdir"
+         debug $userdir
+         for user in `ls -1`; do
+            [ "$user" != "" ] || continue
+            debug "$user $userdir"
+            do_rotate $user $userdir
+            setup_remote_dirs $user $btype $userdir
+            do_user $user $btype $userdir
+         done
+      done
+   fi
 fi
 
 end_mux
-
diff --git a/handlers/mysql.in b/handlers/mysql.in
--- a/handlers/mysql.in
+++ b/handlers/mysql.in
@@ -47,9 +47,9 @@ fi
 
 ignore=''
 for i in $ignores $nodata; do
-       ignore="$ignore --ignore-table=$i"
+   ignore="$ignore --ignore-table=$i"
 done
-	
+
 # create backup dirs, $vroot will be empty if no vsname was specified
 # and we will instead proceed to operate on the host
 [ -d $vroot$backupdir ] || mkdir -p $vroot$backupdir
@@ -59,11 +59,11 @@ dumpdir="$backupdir/sqldump"
 
 if [ $usevserver = yes ]
 then
-	[ "$sqldump" == "no" -o -d $vroot$dumpdir ] || $VSERVER $vsname exec mkdir -p $dumpdir
-	[ "$hotcopy" == "no" -o -d $vroot$hotdir ] || $VSERVER $vsname exec mkdir -p $hotdir
+   [ "$sqldump" == "no" -o -d $vroot$dumpdir ] || $VSERVER $vsname exec mkdir -p $dumpdir
+   [ "$hotcopy" == "no" -o -d $vroot$hotdir ] || $VSERVER $vsname exec mkdir -p $hotdir
 else
-	[ "$sqldump" == "no" -o -d $dumpdir ] || mkdir -p $dumpdir
-	[ "$hotcopy" == "no" -o -d $hotdir ] || mkdir -p $hotdir
+   [ "$sqldump" == "no" -o -d $dumpdir ] || mkdir -p $dumpdir
+   [ "$hotcopy" == "no" -o -d $hotdir ] || mkdir -p $hotdir
 fi
 
 #######################################################################
@@ -87,29 +87,29 @@ defaultsfile=""
 
 if [ "$dbusername" != "" -a "$dbpassword" != "" ]
 then
-    if [ $usevserver = yes ]
-    then
-    	vhome=`$VSERVER $vsname exec getent passwd "root" | @AWK@ -F: '{print $6}'`
-	home="$vroot$vhome"
-    else
-    	home=`getent passwd "root" | @AWK@ -F: '{print $6}'`
-    fi
+   if [ $usevserver = yes ]
+   then
+      vhome=`$VSERVER $vsname exec getent passwd "root" | @AWK@ -F: '{print $6}'`
+   home="$vroot$vhome"
+   else
+      home=`getent passwd "root" | @AWK@ -F: '{print $6}'`
+   fi
 
-    [ -d $home ] || fatal "Can't find root's home directory ($home)."
-    
-    mycnf="$home/.my.cnf"
-    
-    if [ -f $mycnf ]
-    then
-	# rename temporarily
-	tmpcnf="$home/my.cnf.disable"
-	debug "mv $mycnf $tmpcnf"
-	mv $mycnf $tmpcnf
-    fi
-    
-    oldmask=`umask`
-    umask 077
-    cat > $mycnf <<EOF
+   [ -d $home ] || fatal "Can't find root's home directory ($home)."
+
+   mycnf="$home/.my.cnf"
+
+   if [ -f $mycnf ]
+   then
+   # rename temporarily
+   tmpcnf="$home/my.cnf.disable"
+   debug "mv $mycnf $tmpcnf"
+   mv $mycnf $tmpcnf
+   fi
+
+   oldmask=`umask`
+   umask 077
+   cat > $mycnf <<EOF
 # auto generated backupninja mysql conf
 [mysql]
 host=$dbhost
@@ -126,41 +126,41 @@ host=$dbhost
 user=$dbusername
 password="$dbpassword"
 EOF
-	umask $oldmask
-	if [ $usevserver = yes ] 
-	then
-	    defaultsfile="--defaults-extra-file=$vhome/.my.cnf"
-	else
-	    defaultsfile="--defaults-extra-file=$mycnf"
-	fi
+   umask $oldmask
+   if [ $usevserver = yes ]
+   then
+      defaultsfile="--defaults-extra-file=$vhome/.my.cnf"
+   else
+      defaultsfile="--defaults-extra-file=$mycnf"
+   fi
 fi
 
 # if a user is not set, use $configfile, otherwise use $mycnf
 if [ "$user" == "" ]; then
-	user=root;
-	defaultsfile="--defaults-extra-file=$configfile"
+   user=root;
+   defaultsfile="--defaults-extra-file=$configfile"
 else
-	userset=true;
-	if [ $usevserver = yes ]
-	then
-	    vuserhome=`$VSERVER $vsname exec getent passwd "$user" | @AWK@ -F: '{print $6}'`
-	    if [ $? -eq 2 ]
-	    then
-	    	fatal "User $user not found in /etc/passwd"
-	    fi
-    	    userhome="$vroot$vuserhome"
-	else
-	    userhome=`getent passwd "$user" | @AWK@ -F: '{print $6}'`
-	    if [ $? -eq 2 ]
-	    then
-	    	fatal "User $user not found in /etc/passwd"
-	    fi
-       	fi
-	
-	debug "User home set to: $userhome"
-	[ -f $userhome/.my.cnf ] || fatal "Can't find config file in $userhome/.my.cnf"
-	defaultsfile="--defaults-extra-file=$userhome/.my.cnf"
-	debug "using $defaultsfile"
+   userset=true;
+   if [ $usevserver = yes ]
+   then
+      vuserhome=`$VSERVER $vsname exec getent passwd "$user" | @AWK@ -F: '{print $6}'`
+      if [ $? -eq 2 ]
+      then
+         fatal "User $user not found in /etc/passwd"
+      fi
+         userhome="$vroot$vuserhome"
+   else
+      userhome=`getent passwd "$user" | @AWK@ -F: '{print $6}'`
+      if [ $? -eq 2 ]
+      then
+         fatal "User $user not found in /etc/passwd"
+      fi
+         fi
+
+   debug "User home set to: $userhome"
+   [ -f $userhome/.my.cnf ] || fatal "Can't find config file in $userhome/.my.cnf"
+   defaultsfile="--defaults-extra-file=$userhome/.my.cnf"
+   debug "using $defaultsfile"
 fi
 
 #######################################################################
@@ -168,55 +168,55 @@ fi
 
 if [ "$hotcopy" == "yes" ]
 then
-    info "Initializing hotcopy method"
-    if [ "$databases" == "all" ]
-    then
-	if [ $usevserver = yes ]
-	then
-	    	info "dbhost: $dbhost"
-		execstr="$VSERVER $vsname exec $MYSQLHOTCOPY -h $dbhost --quiet --allowold --regexp /.\*/./.\*/ $hotdir"
-	else
-		execstr="$MYSQLHOTCOPY --quiet --allowold --regexp /.\*/./.\*/ $hotdir"
-	fi
-	debug "su $user -c \"$execstr\""
-	if [ ! $test ]
-	then
-		output=`su $user -c "$execstr" 2>&1`
-		code=$?
-		if [ "$code" == "0" ]
-		then
-			debug $output
-			info "Successfully finished hotcopy of all mysql databases"
-		else
-			warning $output
-			warning "Failed to hotcopy all mysql databases"
-		fi
-	fi
-    else	
-	for db in $databases
-	do
-		if [ $usevserver = yes ]
-		then
-			execstr="$VSERVER $vsname exec $MYSQLHOTCOPY --allowold $db $hotdir"
-		else
-			execstr="$MYSQLHOTCOPY --allowold $db $hotdir"
-		fi
-		debug 'su $user -c \"$execstr\"'
-		if [ ! $test ]
-		then
-			output=`su $user -c "$execstr" 2>&1`
-			code=$?
-			if [ "$code" == "0" ]
-			then
-				debug $output
-				info "Successfully finished hotcopy of mysql database $db"
-			else
-				warning $output
-				warning "Failed to hotcopy mysql database $db"
-			fi
-		fi
-	done
-     fi
+   info "Initializing hotcopy method"
+   if [ "$databases" == "all" ]
+   then
+      if [ $usevserver = yes ]
+      then
+         info "dbhost: $dbhost"
+         execstr="$VSERVER $vsname exec $MYSQLHOTCOPY -h $dbhost --quiet --allowold --regexp /.\*/./.\*/ $hotdir"
+      else
+         execstr="$MYSQLHOTCOPY --quiet --allowold --regexp /.\*/./.\*/ $hotdir"
+      fi
+      debug "su $user -c \"$execstr\""
+      if [ ! $test ]
+      then
+         output=`su $user -c "$execstr" 2>&1`
+         code=$?
+         if [ "$code" == "0" ]
+         then
+            debug $output
+            info "Successfully finished hotcopy of all mysql databases"
+         else
+            warning $output
+            warning "Failed to hotcopy all mysql databases"
+         fi
+      fi
+   else
+      for db in $databases
+      do
+         if [ $usevserver = yes ]
+         then
+            execstr="$VSERVER $vsname exec $MYSQLHOTCOPY --allowold $db $hotdir"
+         else
+            execstr="$MYSQLHOTCOPY --allowold $db $hotdir"
+         fi
+         debug 'su $user -c \"$execstr\"'
+         if [ ! $test ]
+         then
+            output=`su $user -c "$execstr" 2>&1`
+            code=$?
+            if [ "$code" == "0" ]
+            then
+               debug $output
+               info "Successfully finished hotcopy of mysql database $db"
+            else
+               warning $output
+               warning "Failed to hotcopy mysql database $db"
+            fi
+         fi
+      done
+   fi
 fi
 
 ##########################################################################
@@ -224,97 +224,97 @@ fi
 
 if [ "$sqldump" == "yes" ]
 then
-    info "Initializing SQL dump method"
-    if [ "$databases" == "all" ]
-    then
-	if [ $usevserver = yes ]
-	then
-	    debug 'echo show databases | $VSERVER $vsname exec su $user -c \"$MYSQL $defaultsfile\" | grep -v Database'
-	    databases=`echo 'show databases' | $VSERVER $vsname exec su $user -c "$MYSQL $defaultsfile" | grep -v Database`
-	    if [ $? -ne 0 ]
-	    then
-	        fatal "Authentication problem, maybe user/password is wrong or mysqld is not running?"
-	    fi
-	else
-		databases=$(su $user -c "$MYSQL $defaultsfile -N -B -e 'show databases'" | sed 's/|//g;/\+----/d')
-		if [ $? -ne 0 ]
-		then
-		    fatal "Authentication problem, maybe user/password is wrong or mysqld is not running?"
-		fi
-	fi
-    fi
+   info "Initializing SQL dump method"
+   if [ "$databases" == "all" ]
+   then
+      if [ $usevserver = yes ]
+      then
+         debug 'echo show databases | $VSERVER $vsname exec su $user -c \"$MYSQL $defaultsfile\" | grep -v Database'
+         databases=`echo 'show databases' | $VSERVER $vsname exec su $user -c "$MYSQL $defaultsfile" | grep -v Database`
+         if [ $? -ne 0 ]
+         then
+            fatal "Authentication problem, maybe user/password is wrong or mysqld is not running?"
+         fi
+      else
+         databases=$(su $user -c "$MYSQL $defaultsfile -N -B -e 'show databases'" | sed 's/|//g;/\+----/d')
+         if [ $? -ne 0 ]
+         then
+            fatal "Authentication problem, maybe user/password is wrong or mysqld is not running?"
+         fi
+      fi
+   fi
 
-	for db in $databases
-	do
-           DUMP_BASE="$MYSQLDUMP $defaultsfile $sqldumpoptions"
+   for db in $databases
+   do
+      DUMP_BASE="$MYSQLDUMP $defaultsfile $sqldumpoptions"
 
-           # Dumping structure and data
-           DUMP="$DUMP_BASE $ignore $db"
+      # Dumping structure and data
+      DUMP="$DUMP_BASE $ignore $db"
 
-           # If requested, dump only the table structure for this database
-           if echo "$nodata" | grep -E '(^|[[:space:]])'"$db\." >/dev/null
-           then
-              # Get the structure of the tables, without data
-              DUMP_STRUCT="$DUMP_BASE --no-data $db"
-              for qualified_table in $nodata
-              do
-                 table=$( expr match "$qualified_table" "$db\.\([^\w]*\)" )
-                 DUMP_STRUCT="$DUMP_STRUCT $table"
-              done
-              DUMP="( $DUMP; $DUMP_STRUCT )"
-           fi
-		if [ $usevserver = yes ]
-		then
-                   # Test to make sure mysqld is running, if it is not sqldump will not work
-                   $VSERVER $vsname exec su $user -c "$MYSQLADMIN $defaultsfile ping 2>&1 >/dev/null"
-                   if [ $? -ne 0 ]; then
-                      fatal "mysqld doesn't appear to be running!"
-                   fi
-                   if [ "$compress" == "yes" ]; then
-                      execstr="$VSERVER $vsname exec $DUMP | $GZIP > $vroot$dumpdir/${db}.sql.gz"
-                   else
-                      execstr="$VSERVER $vsname exec $DUMP -r $vroot$dumpdir/${db}.sql"
-                   fi
-		else
-                   # Test to make sure mysqld is running, if it is not sqldump will not work
-                   su $user -c "$MYSQLADMIN $defaultsfile ping 2>&1 >/dev/null"
-                   if [ $? -ne 0 ]; then
-                      fatal "mysqld doesn't appear to be running!"
-                   fi
-                   if [ "$compress" == "yes" ]; then
-                      execstr="$DUMP | $GZIP > $dumpdir/${db}.sql.gz"
-                   else
-                      execstr="$DUMP -r $dumpdir/${db}.sql"
-                   fi
-		fi
-		debug "su $user -c \"$execstr\""
-		if [ ! $test ]
-		then
-			output=`su $user -c "$execstr" 2>&1`
-			code=$?
-			if [ "$code" == "0" ]
-			then
-				debug $output
-				info "Successfully finished dump of mysql database $db"
-			else
-				warning $output
-				warning "Failed to dump mysql databases $db"
-			fi
-		fi
-	done
+      # If requested, dump only the table structure for this database
+      if echo "$nodata" | grep -E '(^|[[:space:]])'"$db\." >/dev/null
+      then
+         # Get the structure of the tables, without data
+         DUMP_STRUCT="$DUMP_BASE --no-data $db"
+         for qualified_table in $nodata
+         do
+            table=$( expr match "$qualified_table" "$db\.\([^\w]*\)" )
+            DUMP_STRUCT="$DUMP_STRUCT $table"
+         done
+         DUMP="( $DUMP; $DUMP_STRUCT )"
+      fi
+      if [ $usevserver = yes ]
+      then
+         # Test to make sure mysqld is running, if it is not sqldump will not work
+         $VSERVER $vsname exec su $user -c "$MYSQLADMIN $defaultsfile ping 2>&1 >/dev/null"
+         if [ $? -ne 0 ]; then
+            fatal "mysqld doesn't appear to be running!"
+         fi
+         if [ "$compress" == "yes" ]; then
+            execstr="$VSERVER $vsname exec $DUMP | $GZIP > $vroot$dumpdir/${db}.sql.gz"
+         else
+            execstr="$VSERVER $vsname exec $DUMP -r $vroot$dumpdir/${db}.sql"
+         fi
+      else
+         # Test to make sure mysqld is running, if it is not sqldump will not work
+         su $user -c "$MYSQLADMIN $defaultsfile ping 2>&1 >/dev/null"
+         if [ $? -ne 0 ]; then
+            fatal "mysqld doesn't appear to be running!"
+         fi
+         if [ "$compress" == "yes" ]; then
+            execstr="$DUMP | $GZIP > $dumpdir/${db}.sql.gz"
+         else
+            execstr="$DUMP -r $dumpdir/${db}.sql"
+         fi
+      fi
+      debug "su $user -c \"$execstr\""
+      if [ ! $test ]
+      then
+         output=`su $user -c "$execstr" 2>&1`
+         code=$?
+         if [ "$code" == "0" ]
+         then
+            debug $output
+            info "Successfully finished dump of mysql database $db"
+         else
+            warning $output
+            warning "Failed to dump mysql databases $db"
+         fi
+      fi
+   done
 fi
 
 # clean up tmp config file
 if [ "$dbusername" != "" -a "$dbpassword" != "" ]
 then
-	## clean up tmp config file
-	debug "rm $mycnf"
-	rm $mycnf
-	if [ -f "$tmpcnf" ]
-	then
-		debug "mv $tmpcnf $mycnf"
-		mv $tmpcnf $mycnf
-	fi
+   ## clean up tmp config file
+   debug "rm $mycnf"
+   rm $mycnf
+   if [ -f "$tmpcnf" ]
+   then
+      debug "mv $tmpcnf $mycnf"
+      mv $tmpcnf $mycnf
+   fi
 fi
 
 return 0
diff --git a/handlers/pgsql.in b/handlers/pgsql.in
--- a/handlers/pgsql.in
+++ b/handlers/pgsql.in
@@ -36,18 +36,18 @@ if [ $usevserver = yes ]; then
    debug "Examining vserver '$vsname'."
    if [ "$databases" == "all" ]; then
       [ -x "$vroot`$VSERVER $vsname exec which $PGSQLDUMPALL`" ] || \
-	 fatal "Can't find $PGSQLDUMPALL in vserver $vsname."
+         fatal "Can't find $PGSQLDUMPALL in vserver $vsname."
    else
       [ -x "$vroot`$VSERVER $vsname exec which $PGSQLDUMP`" ] || \
-	 fatal "Can't find $PGSQLDUMP in vserver $vsname."
+         fatal "Can't find $PGSQLDUMP in vserver $vsname."
    fi
 else
    if [ "$databases" == "all" ]; then
       [ -x "`which $PGSQLDUMPALL`" ] || \
-	 fatal "Can't find $PGSQLDUMPALL."
+         fatal "Can't find $PGSQLDUMPALL."
    else
       [ -x "`which $PGSQLDUMP`" ] || \
-	 fatal "Can't find $PGSQLDUMP."
+         fatal "Can't find $PGSQLDUMP."
    fi
 fi
 
@@ -64,7 +64,7 @@ else
    pguid=`getent passwd $PGSQLUSER | @AWK@ -F: '{print $3}'`
 fi
 [ -n "$pguid" ] || \
-    fatal "No user called $PGSQLUSER`[ $usevserver = no ] || echo \" on vserver $vsname\"`."
+   fatal "No user called $PGSQLUSER`[ $usevserver = no ] || echo \" on vserver $vsname\"`."
 debug "chown $pguid $vroot$backupdir"
 chown $pguid $vroot$backupdir
 debug "chmod 700 $vroot$backupdir"
@@ -72,61 +72,61 @@ chmod 700 $vroot$backupdir
 
 # if $databases = all, use pg_dumpall
 if [ "$databases" == "all" ]; then
-    if [ $usevserver = yes ]; then
-       if [ "$compress" == "yes" ]; then          
-          execstr="$VSERVER $vsname exec su - $PGSQLUSER -c \"$PGSQLDUMPALL | $GZIP > $backupdir/${vsname}.sql.gz\""
-       else
-          execstr="$VSERVER $vsname exec su - $PGSQLUSER -c \"$PGSQLDUMPALL > $backupdir/${vsname}.sql\""
-       fi
-    else
-       if [ "$compress" == "yes" ]; then
-          execstr="su - $PGSQLUSER -c \"$PGSQLDUMPALL | $GZIP > $backupdir/${localhost}-all.sql.gz\""
-       else
-	execstr="su - $PGSQLUSER -c \"$PGSQLDUMPALL > $backupdir/${localhost}-all.sql\""
-       fi
-    fi
-    debug "$execstr"
-    if [ ! $test ]; then
-       output=`eval $execstr 2>&1`
-       code=$?
-	if [ "$code" == "0" ]; then
-	    debug $output
-	    info "Successfully finished dump of pgsql cluster"
-	else
-	    warning $output
-	    warning "Failed to dump pgsql cluster"
-	fi
-    fi
-    
+   if [ $usevserver = yes ]; then
+      if [ "$compress" == "yes" ]; then
+         execstr="$VSERVER $vsname exec su - $PGSQLUSER -c \"$PGSQLDUMPALL | $GZIP > $backupdir/${vsname}.sql.gz\""
+      else
+         execstr="$VSERVER $vsname exec su - $PGSQLUSER -c \"$PGSQLDUMPALL > $backupdir/${vsname}.sql\""
+      fi
+   else
+      if [ "$compress" == "yes" ]; then
+         execstr="su - $PGSQLUSER -c \"$PGSQLDUMPALL | $GZIP > $backupdir/${localhost}-all.sql.gz\""
+      else
+         execstr="su - $PGSQLUSER -c \"$PGSQLDUMPALL > $backupdir/${localhost}-all.sql\""
+      fi
+   fi
+   debug "$execstr"
+   if [ ! $test ]; then
+      output=`eval $execstr 2>&1`
+      code=$?
+      if [ "$code" == "0" ]; then
+         debug $output
+         info "Successfully finished dump of pgsql cluster"
+      else
+         warning $output
+         warning "Failed to dump pgsql cluster"
+      fi
+   fi
+
 # else use pg_dump on each specified database
 else
-    for db in $databases; do
-	if [ $usevserver = yes ]; then
-           if [ "$compress" == "yes" ]; then
-              execstr="$VSERVER $vsname exec su - $PGSQLUSER -c \"$PGSQLDUMP $db | $GZIP > $backupdir/${db}.sql.gz\""
-           else
-              execstr="$VSERVER $vsname exec su - $PGSQLUSER -c \"$PGSQLDUMP $db | > $backupdir/${db}.sql\""
-           fi
-	else
-           if [ "$compress" == "yes" ]; then
-              execstr="su - $PGSQLUSER -c \"$PGSQLDUMP $db | $GZIP > $backupdir/${db}.sql.gz\""
-           else
-              execstr="su - $PGSQLUSER -c \"$PGSQLDUMP $db > $backupdir/${db}.sql\""
-           fi
-	fi
-	debug "$execstr"
-	if [ ! $test ]; then
-	    output=`eval $execstr 2>&1`
-	    code=$?
-	    if [ "$code" == "0" ]; then
-		debug $output
-		info "Successfully finished dump of pgsql database ${db}"
-	    else
-		warning $output
-		warning "Failed to dump pgsql database ${db}"
-	    fi
-	fi
-    done
+   for db in $databases; do
+      if [ $usevserver = yes ]; then
+         if [ "$compress" == "yes" ]; then
+            execstr="$VSERVER $vsname exec su - $PGSQLUSER -c \"$PGSQLDUMP $db | $GZIP > $backupdir/${db}.sql.gz\""
+         else
+            execstr="$VSERVER $vsname exec su - $PGSQLUSER -c \"$PGSQLDUMP $db | > $backupdir/${db}.sql\""
+         fi
+      else
+         if [ "$compress" == "yes" ]; then
+            execstr="su - $PGSQLUSER -c \"$PGSQLDUMP $db | $GZIP > $backupdir/${db}.sql.gz\""
+         else
+            execstr="su - $PGSQLUSER -c \"$PGSQLDUMP $db > $backupdir/${db}.sql\""
+         fi
+      fi
+      debug "$execstr"
+      if [ ! $test ]; then
+         output=`eval $execstr 2>&1`
+         code=$?
+         if [ "$code" == "0" ]; then
+            debug $output
+            info "Successfully finished dump of pgsql database ${db}"
+         else
+            warning $output
+            warning "Failed to dump pgsql database ${db}"
+         fi
+      fi
+   done
 fi
 
 return 0
diff --git a/handlers/rdiff.in b/handlers/rdiff.in
--- a/handlers/rdiff.in
+++ b/handlers/rdiff.in
@@ -7,68 +7,68 @@
 ### FUNCTIONS ###
 
 function test_connection() {
-	# given a user and host,
-	# tests the connection.
-	# if user or host is missing, returns 0
-	# (ie, assume it's a local connection).
-	if [ $# -lt 2 ]; then
-		debug "(local is assumed to be a good connection)"
-		return 0
-	fi
-	local user=$1
-	local host=$2
-	debug "ssh $sshoptions -o PasswordAuthentication=no $host -l $user 'echo -n 1'"
-	local ret=`ssh $sshoptions -o PasswordAuthentication=no $host -l $user 'echo -n host is alive'`
-	if echo $ret | grep "host is alive"; then
-		debug "Connected to $host as $user successfully"
-	else
-		fatal "Can't connect to $host as $user."
-	fi
+   # given a user and host,
+   # tests the connection.
+   # if user or host is missing, returns 0
+   # (ie, assume it's a local connection).
+   if [ $# -lt 2 ]; then
+      debug "(local is assumed to be a good connection)"
+      return 0
+   fi
+   local user=$1
+   local host=$2
+   debug "ssh $sshoptions -o PasswordAuthentication=no $host -l $user 'echo -n 1'"
+   local ret=`ssh $sshoptions -o PasswordAuthentication=no $host -l $user 'echo -n host is alive'`
+   if echo $ret | grep "host is alive"; then
+      debug "Connected to $host as $user successfully"
+   else
+      fatal "Can't connect to $host as $user."
+   fi
 }
 
 function get_version() {
-	# given no arguments, returns the local version.
-	# given a user and host, returns the remote version.
-	# if user or host is missing, returns the local version.
-	if [ "$#" -lt 2 ]; then
-		debug "$RDIFFBACKUP -V"
-		echo `$RDIFFBACKUP -V`
-	else
-		local user=$1
-		local host=$2
-		debug "ssh $sshoptions $host -l $user '$RDIFFBACKUP -V'"
-		echo `ssh $sshoptions $host -l $user "$RDIFFBACKUP -V | grep rdiff-backup"`
-	fi
+   # given no arguments, returns the local version.
+   # given a user and host, returns the remote version.
+   # if user or host is missing, returns the local version.
+   if [ "$#" -lt 2 ]; then
+      debug "$RDIFFBACKUP -V"
+      echo `$RDIFFBACKUP -V`
+   else
+      local user=$1
+      local host=$2
+      debug "ssh $sshoptions $host -l $user '$RDIFFBACKUP -V'"
+      echo `ssh $sshoptions $host -l $user "$RDIFFBACKUP -V | grep rdiff-backup"`
+   fi
 }
 
 function check_consistency() {
-	local section=$1
-	local type=$2
-	local user=$3
-	local host=$4
-	if [ "$type" == "local" ]; then
-		if [ "$user" != "" ]; then
-			warning "User should not be specified for local $section."
-		fi
-		if [ "$host" != "" ]; then
-			warning "Host should not be specified for local $section."
-		fi
-	fi
-	if [ "$type" == "remote" ]; then
-		if [ "$user" == "" ]; then
-			fatal "User must be specified for remote $section."
-		fi
-		if [ "host" == "" ]; then
-			fatal "Host must be specifed for remote $section."
-		fi
-	fi
+   local section=$1
+   local type=$2
+   local user=$3
+   local host=$4
+   if [ "$type" == "local" ]; then
+      if [ "$user" != "" ]; then
+         warning "User should not be specified for local $section."
+      fi
+      if [ "$host" != "" ]; then
+         warning "Host should not be specified for local $section."
+      fi
+   fi
+   if [ "$type" == "remote" ]; then
+      if [ "$user" == "" ]; then
+         fatal "User must be specified for remote $section."
+      fi
+      if [ "host" == "" ]; then
+         fatal "Host must be specifed for remote $section."
+      fi
+   fi
 }
 
 function check_cstream() {
-	local cstream=$1
-	if [ ! -x $cstream ]; then
-		fatal "Can't find your cstream binary (trying: $cstream). If you use bwlimit you must have cstream installed."
-	fi
+   local cstream=$1
+   if [ ! -x $cstream ]; then
+      fatal "Can't find your cstream binary (trying: $cstream). If you use bwlimit you must have cstream installed."
+   fi
 }
 
 ### GET CONFIG ###
@@ -102,7 +102,7 @@ getconf sshoptions
 check_consistency "destination" "$type" "$user" "$host"
 
 if [ -n "$sshoptions" ] && echo $options | grep -qv "remote-schema"; then
-	options="$options --remote-schema 'ssh -C $sshoptions %s rdiff-backup --server'"
+   options="$options --remote-schema 'ssh -C $sshoptions %s rdiff-backup --server'"
 fi
 
 ### CHECK CONFIG ###
@@ -114,7 +114,7 @@ if [ $vservers_are_available = yes ]; then
       vsnames="$found_vservers"
    else
       if ! vservers_exist "$vsnames" ; then
-            fatal "At least one of the vservers listed in vsnames ($vsnames) does not exist."
+         fatal "At least one of the vservers listed in vsnames ($vsnames) does not exist."
       fi
    fi
    if [ -n "$vsinclude" ]; then
@@ -128,40 +128,40 @@ fi
 # check the connection at the source and destination
 [ -n "$test" ] || test=0
 if [ "$testconnect" = "yes" ] || [ "${test}" -eq 1 ]; then
-	test_connection $sourceuser $sourcehost
-	test_connection $destuser $desthost
+   test_connection $sourceuser $sourcehost
+   test_connection $destuser $desthost
 fi
 
 if [ "$ignore_version" != "yes" ]; then
-	# see that rdiff-backup has the same version at the source and destination
-	sourceversion=`get_version $sourceuser $sourcehost`
-	destversion=`get_version $destuser $desthost`
-	if [ "$sourceversion" != "$destversion" ]; then
-		fatal "rdiff-backup does not have the same version at the source and at the destination."
-	fi
+   # see that rdiff-backup has the same version at the source and destination
+   sourceversion=`get_version $sourceuser $sourcehost`
+   destversion=`get_version $destuser $desthost`
+   if [ "$sourceversion" != "$destversion" ]; then
+      fatal "rdiff-backup does not have the same version at the source and at the destination."
+   fi
 fi
 
 # source specific checks
-case $sourcetype in 
-	remote ) execstr_sourcepart="$sourceuser@$sourcehost::/" ;;
-	local  ) execstr_sourcepart="/" ;;
-	*      ) fatal "sourcetype '$sourcetype' is neither local nor remote" ;;
+case $sourcetype in
+   remote ) execstr_sourcepart="$sourceuser@$sourcehost::/" ;;
+   local  ) execstr_sourcepart="/" ;;
+   *      ) fatal "sourcetype '$sourcetype' is neither local nor remote" ;;
 esac
 
 # destination specific checks
 [ "$destdir" != "" ] || fatal "Destination directory not set"
-case $desttype in 
-	remote ) execstr_destpart="$destuser@$desthost::$destdir/$label" ;;
-	local  ) execstr_destpart="$destdir/$label" ;;
-	*      ) fatal "desttype '$desttype' is neither local nor remote" ;;
+case $desttype in
+   remote ) execstr_destpart="$destuser@$desthost::$destdir/$label" ;;
+   local  ) execstr_destpart="$destdir/$label" ;;
+   *      ) fatal "desttype '$desttype' is neither local nor remote" ;;
 esac
-	
+
 ### REMOVE OLD BACKUPS ###
 
 if [ "$keep" != yes ]; then
 
    if [ "`echo $keep | tr -d 0-9`" == "" ]; then
-	# add D if no other date unit is specified
+   # add D if no other date unit is specified
       keep="${keep}D"
    fi
 
@@ -175,27 +175,27 @@ if [ "$keep" != yes ]; then
    if [ $test = 0 ]; then
       output="`su -c "$removestr" 2>&1`"
       if [ $? = 0 ]; then
-	 debug $output
-	 info "Removing backups older than $keep days succeeded."
+         debug $output
+         info "Removing backups older than $keep days succeeded."
       else
-	 warning $output
-	 warning "Failed removing backups older than $keep."
+         warning $output
+         warning "Failed removing backups older than $keep."
       fi
    fi
 
 fi
 
-# Add cstream 
+# Add cstream
 
 if [ ! -z $bwlimit ]; then
-	check_cstream $CSTREAM;
-	if [ "$desttype" = "remote" ]; then
-		RDIFFBACKUP="$RDIFFBACKUP --remote-schema 'cstream -t $bwlimit | ssh %s \''rdiff-backup --server\'''"
-	elif [ "$sourcetype" = "remote" ]; then
-		RDIFFBACKUP="$RDIFFBACKUP --remote-schema 'ssh %s \''rdiff-backup --server\'' | cstream -t $bwlimit'"
-	else
-		fatal "You specified a bandwidth limit but neither your source nor destination types are remote."
-	fi
+   check_cstream $CSTREAM;
+   if [ "$desttype" = "remote" ]; then
+      RDIFFBACKUP="$RDIFFBACKUP --remote-schema 'cstream -t $bwlimit | ssh %s \''rdiff-backup --server\'''"
+   elif [ "$sourcetype" = "remote" ]; then
+      RDIFFBACKUP="$RDIFFBACKUP --remote-schema 'ssh %s \''rdiff-backup --server\'' | cstream -t $bwlimit'"
+   else
+      fatal "You specified a bandwidth limit but neither your source nor destination types are remote."
+   fi
 fi
 
 ### EXECUTE ###
@@ -212,7 +212,7 @@ for i in $exclude; do
    str="${i//__star__/*}"
    execstr="${execstr}--exclude '$str' "
 done
-# includes 
+# includes
 for i in $include; do
    [ "$i" != "/" ] || fatal "Sorry, you cannot use 'include = /'"
    str="${i//__star__/*}"
@@ -223,10 +223,10 @@ done
 if [ $usevserver = yes ]; then
    for vserver in $vsnames; do
       for vi in $vsinclude; do
-	 str="${vi//__star__/*}"
-	 str="$VROOTDIR/$vserver$str"
+         str="${vi//__star__/*}"
+         str="$VROOTDIR/$vserver$str"
          if [ -n "$str" ]; then
-	    execstr="${execstr}--include '$str' "
+            execstr="${execstr}--include '$str' "
          else
             warning "vsinclude statement '${vi//__star__/*}' will be ignored for VServer $vserver. $symlinks_warning"
          fi
@@ -238,20 +238,20 @@ set +o noglob
 
 # exclude everything else
 [ "$include" != "" -o "$vsinclude" != "" ] && execstr="${execstr}--exclude '/*' "
-		
+
 # include client-part and server-part
 execstr="${execstr}$execstr_sourcepart $execstr_destpart"
 
 debug "$execstr"
 if [ $test = 0 ]; then
-	output=`nice -n $nicelevel su -c "$execstr" 2>&1`
-	if [ $? = 0 ]; then
-		debug $output
-		info "Successfully finished backing up source $label"
-	else
-		warning $output
-		warning "Failed backup up source $label"
-	fi
-fi	
+   output=`nice -n $nicelevel su -c "$execstr" 2>&1`
+   if [ $? = 0 ]; then
+      debug $output
+      info "Successfully finished backing up source $label"
+   else
+      warning $output
+      warning "Failed backup up source $label"
+   fi
+fi
 
 return 0
diff --git a/handlers/rsync.in b/handlers/rsync.in
--- a/handlers/rsync.in
+++ b/handlers/rsync.in
@@ -102,40 +102,40 @@ getconf service
 
 function rotate {
 
-  if [[ "$2" < 4 ]]; then
-    error "Rotate: minimum of 4 rotations"
-    exit 1
-  fi
+   if [[ "$2" < 4 ]]; then
+      error "Rotate: minimum of 4 rotations"
+      exit 1
+   fi
 
-  if [ -d $1.$2 ]; then
-    $nice $mv /$1.$2 /$1.tmp
-  fi
+   if [ -d $1.$2 ]; then
+      $nice $mv /$1.$2 /$1.tmp
+   fi
 
-  for ((n=`echo "$2 - 1" | bc`; n >= 0; n--)); do
-    if [ -d $1.$n ]; then
-      dest=`echo "$n + 1" | bc`
-      $nice $mv /$1.$n /$1.$dest
-      $touch /$1.$dest
-    fi
-  done
+   for ((n=`echo "$2 - 1" | bc`; n >= 0; n--)); do
+      if [ -d $1.$n ]; then
+         dest=`echo "$n + 1" | bc`
+         $nice $mv /$1.$n /$1.$dest
+         $touch /$1.$dest
+      fi
+   done
 
-  if [ -d $1.tmp ]; then
-    $nice $mv /$1.tmp /$1.0
-  fi
+   if [ -d $1.tmp ]; then
+      $nice $mv /$1.tmp /$1.0
+   fi
 
-  if [ -d $1.1 ]; then
-    $nice $cp -alf /$1.1/. /$1.0
-  fi
+   if [ -d $1.1 ]; then
+      $nice $cp -alf /$1.1/. /$1.0
+   fi
 
 }
 
 function move_files {
 
- ref=$tmp/makesnapshot-mymv-$$;
- $touch -r $1 $ref;
- $mv $1 $2;
- $touch -r $ref $2;
- $rm $ref;
+   ref=$tmp/makesnapshot-mymv-$$;
+   $touch -r $1 $ref;
+   $mv $1 $2;
+   $touch -r $ref $2;
+   $rm $ref;
 
 }
 
@@ -143,54 +143,54 @@ backupdir="$mountpoint/$backupdir"
 
 # does $backupdir exists?
 
-if [ ! -d "$backupdir" ]; then 
-  error "Backupdir $backupdir does not exist"
-  exit 1
+if [ ! -d "$backupdir" ]; then
+   error "Backupdir $backupdir does not exist"
+   exit 1
 fi
 
 # setup number of increments
 
 if [ -z "$days" ]; then
-  keep="4"
+   keep="4"
 else
-  keep="`echo $days - 1 | bc -l`"
+   keep="`echo $days - 1 | bc -l`"
 fi
 
 # lockfile setup
 
 if [ ! -z "$lockfile" ]; then
-  $touch $lockfile || warning "Could not create lockfile $lockfile"
+   $touch $lockfile || warning "Could not create lockfile $lockfile"
 fi
 
 # nicelevel setup
 
-if [ ! -z "$nicelevel" ]; then 
-  nice="nice -n $nicelevel"
-else 
-  nice=""
+if [ ! -z "$nicelevel" ]; then
+   nice="nice -n $nicelevel"
+else
+   nice=""
 fi
 
 # connection test
 
 if [ "$from" == "remote" ] && [ "$testconnect" == "yes" ]; then
-  debug "$ssh -o PasswordAuthentication=no $user@$host 'echo -n 1'"
-  result=`ssh -o PasswordAuthentication=no $user@$host 'echo -n 1'`
-  if [ "$result" != "1" ]; then
-    fatal "Can't connect to $host as $user."
-  else
-    debug "Connected to $srchost successfully"
-  fi
+   debug "$ssh -o PasswordAuthentication=no $user@$host 'echo -n 1'"
+   result=`ssh -o PasswordAuthentication=no $user@$host 'echo -n 1'`
+   if [ "$result" != "1" ]; then
+      fatal "Can't connect to $host as $user."
+   else
+      debug "Connected to $srchost successfully"
+   fi
 fi
 
 # rsync options for local sources
 
 if [ "$from" == "local" ]; then
 
-  rsync_local_options="$rsync_options"
+   rsync_local_options="$rsync_options"
 
-  if [ ! -z "$numericids" ]; then
-    rsync_local_options="$rsync_local_options --numeric-ids "
-  fi
+   if [ ! -z "$numericids" ]; then
+      rsync_local_options="$rsync_local_options --numeric-ids "
+   fi
 
 fi
 
@@ -198,41 +198,41 @@ fi
 
 if [ "$from" == "remote" ]; then
 
-  rsync_remote_options="$rsync_options --rsync-path=$remote_rsync"
+   rsync_remote_options="$rsync_options --rsync-path=$remote_rsync"
 
-  if [ "$compress" == "1" ]; then
-    rsync_remote_options="$rsync_remote_options --compress"
-  fi
+   if [ "$compress" == "1" ]; then
+      rsync_remote_options="$rsync_remote_options --compress"
+   fi
 
-  if [ ! -z "$bandwidthlimit" ]; then
-    rsync_remote_options="$rsync_remote_options --bwlimit=$bandwidthlimit"
-  fi
+   if [ ! -z "$bandwidthlimit" ]; then
+      rsync_remote_options="$rsync_remote_options --bwlimit=$bandwidthlimit"
+   fi
 
-  if [ ! -z "$numericids" ]; then
-    rsync_remote_options="$rsync_remote_options --numeric-ids"
-  fi
+   if [ ! -z "$numericids" ]; then
+      rsync_remote_options="$rsync_remote_options --numeric-ids"
+   fi
 
 fi
 
 # set mv procedure
 
 if [ $enable_mv_timestamp_bug == "yes" ]; then
-  mv=move_files
+   mv=move_files
 fi
 
 # set excludes
 
 for path in $exclude; do
-  EXCLUDES="$EXCLUDES --exclude=$path"
+   EXCLUDES="$EXCLUDES --exclude=$path"
 done
 
 # stop services
 
 if [ ! -z "$service" ]; then
-  for daemon in $service; do
-    info "Stopping service $daemon..."
-    $initscripts/$daemon stop
-  done
+   for daemon in $service; do
+      info "Stopping service $daemon..."
+      $initscripts/$daemon stop
+   done
 fi
 
 echo "Starting backup at `date`" >> $log
@@ -240,110 +240,110 @@ echo "Starting backup at `date`" >> $log
 # mount backup destination folder as read-write
 
 if [ "$read_only" == "1" ] || [ "$read_only" == "yes" ]; then
-  if [ -d "$mountpoint" ]; then
-    mount -o remount,rw $mountpoint
-    if (($?)); then
-      error "Could not mount $mountpoint"
-      exit 1
-    fi
-  fi
+   if [ -d "$mountpoint" ]; then
+      mount -o remount,rw $mountpoint
+      if (($?)); then
+         error "Could not mount $mountpoint"
+         exit 1
+      fi
+   fi
 fi
 
 # add vservers to included folders
 
 if [ "$vservers_are_available" == "yes" ]; then
 
-  # sane permission on backup
-  mkdir -p $backupdir/$VROOTDIR
-  chmod 000 $backupdir/$VROOTDIR
+   # sane permission on backup
+   mkdir -p $backupdir/$VROOTDIR
+   chmod 000 $backupdir/$VROOTDIR
 
-  for candidate in $found_vservers; do
-    candidate="`basename $candidate`"
-    found_excluded_vserver="0"
-    for excluded_vserver in $exclude_vserver; do
-      if [ "$excluded_vserver" == "$candidate" ]; then
-        found_excluded_vserver="1"
-        break
+   for candidate in $found_vservers; do
+      candidate="`basename $candidate`"
+      found_excluded_vserver="0"
+      for excluded_vserver in $exclude_vserver; do
+         if [ "$excluded_vserver" == "$candidate" ]; then
+            found_excluded_vserver="1"
+            break
+         fi
+      done
+      if [ "$found_excluded_vserver" == "0" ]; then
+         include="$include $VROOTDIR/$candidate"
       fi
-    done
-    if [ "$found_excluded_vserver" == "0" ]; then
-      include="$include $VROOTDIR/$candidate"
-    fi
-  done
+   done
 fi
 
 # the backup procedure
 
 for SECTION in $include; do
 
-  section="`basename $SECTION`"
+   section="`basename $SECTION`"
 
-  if [ ! -d "$backupdir/$SECTION/$section.0" ]; then
-    mkdir -p $backupdir/$SECTION/$section.0
-  fi
- 
-  info "Rotating $backupdir/$SECTION/$section..."
-  echo "Rotating $backupdir/$SECTION/$section..." >> $log
-  rotate $backupdir/$SECTION/$section $keep
-  info "Syncing $SECTION on $backupdir/$SECTION/$section.0..."
+   if [ ! -d "$backupdir/$SECTION/$section.0" ]; then
+      mkdir -p $backupdir/$SECTION/$section.0
+   fi
 
-  if [ "$from" == "local" ]; then
-    debug $rsync $rsync_local_options $EXCLUDES /$SECTION/ $backupdir/$SECTION/$section.0/ 
-    $nice $rsync $rsync_local_options $EXCLUDES /$SECTION/ $backupdir/$SECTION/$section.0/ >> $log
-    if [ "$?" != "0" ]; then
-      warning "Rsync error when trying to transfer $SECTION"
-    fi
-  elif [ "$from" == "remote" ]; then
-    if [ -z "$user" ] || [ -z "$host" ]; then
-      error "Config file error: either user or host was not specified"
-      exit 1
-    else
-      debug $nice $rsync $rsync_remote_options $EXCLUDES -e "$ssh" $user@$host:/$SECTION/ $backupdir/$SECTION/$section.0
-      $nice $rsync $rsync_remote_options $EXCLUDES -e "$ssh" $user@$host:/$SECTION/ $backupdir/$SECTION/$section.0 >> $log
+   info "Rotating $backupdir/$SECTION/$section..."
+   echo "Rotating $backupdir/$SECTION/$section..." >> $log
+   rotate $backupdir/$SECTION/$section $keep
+   info "Syncing $SECTION on $backupdir/$SECTION/$section.0..."
+
+   if [ "$from" == "local" ]; then
+      debug $rsync $rsync_local_options $EXCLUDES /$SECTION/ $backupdir/$SECTION/$section.0/
+      $nice $rsync $rsync_local_options $EXCLUDES /$SECTION/ $backupdir/$SECTION/$section.0/ >> $log
       if [ "$?" != "0" ]; then
-        warning "Rsync error when trying to transfer $SECTION"
+         warning "Rsync error when trying to transfer $SECTION"
       fi
-    fi
-  else
-    error "Invalid source $from"
-    exit 1
-  fi
+   elif [ "$from" == "remote" ]; then
+      if [ -z "$user" ] || [ -z "$host" ]; then
+         error "Config file error: either user or host was not specified"
+         exit 1
+      else
+         debug $nice $rsync $rsync_remote_options $EXCLUDES -e "$ssh" $user@$host:/$SECTION/ $backupdir/$SECTION/$section.0
+         $nice $rsync $rsync_remote_options $EXCLUDES -e "$ssh" $user@$host:/$SECTION/ $backupdir/$SECTION/$section.0 >> $log
+         if [ "$?" != "0" ]; then
+            warning "Rsync error when trying to transfer $SECTION"
+            fi
+      fi
+   else
+      error "Invalid source $from"
+      exit 1
+   fi
 
-  $touch $backupdir/$SECTION/$section.0
+   $touch $backupdir/$SECTION/$section.0
 
 done
 
 # remount backup destination as read-only
 
 if [ "$read_only" == "1" ] || [ "$read_only" == "yes" ]; then
-  mount -o remount,ro $mountpoint
+   mount -o remount,ro $mountpoint
 fi
 
 # check partition for errors
 
 if [ "$fscheck" == "1" ] || [ "$fscheck" == "yes" ]; then
-  umount $mountpoint
-  if (($?)); then
-    warning "Could not umount $mountpoint to run fsck"
-  else
-    $nice $fsck -v -y $partition >> $log
-    mount $mountpoint
-  fi
+   umount $mountpoint
+   if (($?)); then
+      warning "Could not umount $mountpoint to run fsck"
+   else
+      $nice $fsck -v -y $partition >> $log
+      mount $mountpoint
+   fi
 fi
 
 # restart services
 
 if [ ! -z "$service" ]; then
-  for daemon in $service; do
-    info "Starting service $daemon..."
-    $initscripts/$daemon start
-  done
+   for daemon in $service; do
+      info "Starting service $daemon..."
+      $initscripts/$daemon start
+   done
 fi
 
 # removes the lockfile
 
 if [ ! -z "$lockfile" ]; then
-  $rm $lockfile || warning "Could not remove lockfile $lockfile"
+   $rm $lockfile || warning "Could not remove lockfile $lockfile"
 fi
 
 echo "Finnishing backup at `date`" >> $log
diff --git a/handlers/svn.in b/handlers/svn.in
--- a/handlers/svn.in
+++ b/handlers/svn.in
@@ -7,7 +7,7 @@ getconf src /var/lib/svn
 getconf dest /var/backups/svn
 getconf tmp /var/backups/svn.tmp
 getconf HOTBACKUP "/usr/bin/svnadmin hotcopy"
-getconf vsname	
+getconf vsname
 
 error=0
 
@@ -35,43 +35,43 @@ fi
 cd $vroot$src
 for repo in `find . -name svnserve.conf`
 do
-    repo=`dirname $repo`
-    repo=`dirname $repo`
+   repo=`dirname $repo`
+   repo=`dirname $repo`
 
-    ret=`mkdir -p $vroot$tmp/$repo 2>&1`
-    code=$?
-    if [ "$ret" ]; then
-       debug "$ret"
-    fi
-    if [ $code != 0 ]; then   
-       error "command failed mkdir -p $vroot$tmp/$repo"
-    fi
+   ret=`mkdir -p $vroot$tmp/$repo 2>&1`
+   code=$?
+   if [ "$ret" ]; then
+      debug "$ret"
+   fi
+   if [ $code != 0 ]; then
+      error "command failed mkdir -p $vroot$tmp/$repo"
+   fi
 
-    if [ $usevserver = yes ]
-    then
-	ret=`$VSERVER $vsname exec $HOTBACKUP $src/$repo $tmp/$repo 2>&1`
-    else
-	ret=`$HOTBACKUP $src/$repo $tmp/$repo 2>&1`
-    fi
-    code=$?
-    if [ "$ret" ]; then
-       debug "$ret"
-    fi
-    if [ $code != 0 ]; then
-       error "command failed -- $HOTBACKUP $vroot$src/$repo $vroot$tmp/$repo"
-       error=1
-    fi
+   if [ $usevserver = yes ]
+   then
+      ret=`$VSERVER $vsname exec $HOTBACKUP $src/$repo $tmp/$repo 2>&1`
+   else
+      ret=`$HOTBACKUP $src/$repo $tmp/$repo 2>&1`
+   fi
+   code=$?
+   if [ "$ret" ]; then
+      debug "$ret"
+   fi
+   if [ $code != 0 ]; then
+      error "command failed -- $HOTBACKUP $vroot$src/$repo $vroot$tmp/$repo"
+      error=1
+   fi
 done
 
 if [ $error -eq 1 ]; then
-    echo "Error: because of earlier errors, we are leaving svn backups in $vroot$tmp instead of $vroot$dest"
+   echo "Error: because of earlier errors, we are leaving svn backups in $vroot$tmp instead of $vroot$dest"
 else
-    if [ -d $vroot$dest -a -d $vroot$tmp ]; then
-        rm -rf $vroot$dest
-    fi
-    if [ -d $vroot$tmp ]; then
-        mv $vroot$tmp $vroot$dest
-    fi
+   if [ -d $vroot$dest -a -d $vroot$tmp ]; then
+      rm -rf $vroot$dest
+   fi
+   if [ -d $vroot$tmp ]; then
+      mv $vroot$tmp $vroot$dest
+   fi
 fi
 
 exit 0
diff --git a/handlers/trac.in b/handlers/trac.in
--- a/handlers/trac.in
+++ b/handlers/trac.in
@@ -12,39 +12,38 @@ getconf tmp /var/backups/trac.tmp
 cd $src
 for repo in `find . -name VERSION`
 do
+   repo=`dirname $repo`
+   if [ "$repo" == "." ]
+   then
+      repo=""
+   fi
 
-    repo=`dirname $repo`
-    if [ "$repo" == "." ]
-    then 
-       repo="" 
-    fi
+   # Just make the parent directory for $tmp/$repo
+   parentdir=`dirname $tmp/$repo`
+   ret=`mkdir -p $parentdir 2>&1`
+   code=$?
+   if [ "$ret" ]; then
+      debug "$ret"
+   fi
+   if [ $code != 0 ]; then
+      error "command failed mkdir -p $parentdir"
+   fi
 
-    # Just make the parent directory for $tmp/$repo
-    parentdir=`dirname $tmp/$repo`
-    ret=`mkdir -p $parentdir 2>&1`
-    code=$?
-    if [ "$ret" ]; then
-       debug "$ret"
-    fi
-    if [ $code != 0 ]; then
-       error "command failed mkdir -p $parentdir"
-    fi
-
-    ret=`trac-admin $src/$repo hotcopy $tmp/$repo 2>&1`
-    code=$?
-    if [ "$ret" ]; then
-       debug "$ret"
-    fi
-    if [ $code != 0 ]; then
-       error "command failed -- trac-admin $src/$repo hotcopy $tmp/$repo"
-    fi
+   ret=`trac-admin $src/$repo hotcopy $tmp/$repo 2>&1`
+   code=$?
+   if [ "$ret" ]; then
+      debug "$ret"
+   fi
+   if [ $code != 0 ]; then
+      error "command failed -- trac-admin $src/$repo hotcopy $tmp/$repo"
+   fi
 done
 
 if [ -d $dest -a -d $tmp ]; then
-     rm -rf $dest
+   rm -rf $dest
 fi
 if [ -d $tmp ]; then
-     mv $tmp $dest
+   mv $tmp $dest
 fi
 
 exit 0
diff --git a/handlers/wget b/handlers/wget
--- a/handlers/wget
+++ b/handlers/wget
@@ -77,84 +77,82 @@ getconf folder
 
 function rotate {
 
-  if [[ "$2" < 4 ]]; then
-    error "Rotate: minimum of 4 rotations"
-    exit 1
-  fi
+   if [[ "$2" < 4 ]]; then
+      error "Rotate: minimum of 4 rotations"
+      exit 1
+   fi
 
-  if [ -d $1.$2 ]; then
-    $nice $mv /$1.$2 /$1.tmp
-  fi
+   if [ -d $1.$2 ]; then
+      $nice $mv /$1.$2 /$1.tmp
+   fi
 
-  for ((n=`echo "$2 - 1" | bc`; n >= 0; n--)); do
-    if [ -d $1.$n ]; then
-      dest=`echo "$n + 1" | bc`
-      $nice $mv /$1.$n /$1.$dest
-      $touch /$1.$dest
-    fi
-  done
+   for ((n=`echo "$2 - 1" | bc`; n >= 0; n--)); do
+      if [ -d $1.$n ]; then
+         dest=`echo "$n + 1" | bc`
+         $nice $mv /$1.$n /$1.$dest
+         $touch /$1.$dest
+      fi
+   done
 
-  if [ -d $1.tmp ]; then
-    $nice $mv /$1.tmp /$1.0
-  fi
+   if [ -d $1.tmp ]; then
+      $nice $mv /$1.tmp /$1.0
+   fi
 
-  if [ -d $1.1 ]; then
-    $nice $cp -alf /$1.1/. /$1.0
-  fi
+   if [ -d $1.1 ]; then
+      $nice $cp -alf /$1.1/. /$1.0
+   fi
 
 }
 
 function move_files {
-
- ref=$tmp/makesnapshot-mymv-$$;
- $touch -r $1 $ref;
- $mv $1 $2;
- $touch -r $ref $2;
- $rm $ref;
-
+   ref=$tmp/makesnapshot-mymv-$$;
+   $touch -r $1 $ref;
+   $mv $1 $2;
+   $touch -r $ref $2;
+   $rm $ref;
 }
 
 backupdir="$mountpoint/$backupdir"
 
 # does $backupdir exists?
 
-if [ ! -d "$backupdir" ]; then 
-  error "Backupdir $backupdir does not exist"
-  exit 1
+if [ ! -d "$backupdir" ]; then
+   error "Backupdir $backupdir does not exist"
+   exit 1
 fi
 
 # setup number of increments
 
 if [ -z "$days" ]; then
-  keep="4"
+   keep="4"
 else
-  keep="`echo $days - 1 | bc -l`"
+   keep="`echo $days - 1 | bc -l`"
 fi
 
 # lockfile setup
 
 if [ ! -z "$lockfile" ]; then
-  $touch $lockfile || warning "Could not create lockfile $lockfile"
+   $touch $lockfile || warning "Could not create lockfile $lockfile"
 fi
 
 # nicelevel setup
 
-if [ ! -z "$nicelevel" ]; then 
-  nice="nice -n $nicelevel"
-else 
-  nice=""
+if [ ! -z "$nicelevel" ]; then
+   nice="nice -n $nicelevel"
+else
+   nice=""
 fi
 
 # set mv procedure
 
 if [ $enable_mv_timestamp_bug == "yes" ]; then
-  mv=move_files
+   mv=move_files
 fi
 
 # set excludes
 
 for path in $exclude; do
-  EXCLUDES="$EXCLUDES --exclude=$path"
+   EXCLUDES="$EXCLUDES --exclude=$path"
 done
 
 echo "Starting backup at `date`" >> $log
@@ -162,19 +160,19 @@ echo "Starting backup at `date`" >> $log
 # mount backup destination folder as read-write
 
 if [ "$read_only" == "1" ] || [ "$read_only" == "yes" ]; then
-  if [ -d "$mountpoint" ]; then
-    mount -o remount,rw $mountpoint
-    if (($?)); then
-      error "Could not mount $mountpoint"
-      exit 1
-    fi
-  fi
+   if [ -d "$mountpoint" ]; then
+      mount -o remount,rw $mountpoint
+      if (($?)); then
+         error "Could not mount $mountpoint"
+         exit 1
+      fi
+   fi
 fi
 
 # the backup procedure
 
 if [ ! -d "$backupdir/$folder/$folder.0" ]; then
-  mkdir -p $backupdir/$folder/$folder.0
+   mkdir -p $backupdir/$folder/$folder.0
 fi
 
 info "Rotating $backupdir/$folder/$folder..."
@@ -183,7 +181,7 @@ rotate $backupdir/$folder/$folder $keep
 info "Wget'ing $SECTION on $backupdir/$folder/$folder.0..."
 
 if [ ! -z "$badnwidth" ]; then
-  limit_rate="--limit-rate=$badnwidth""k"
+   limit_rate="--limit-rate=$badnwidth""k"
 fi
 
 cd $backupdir/$folder/$folder.0
@@ -195,25 +193,25 @@ $touch $backupdir/$folder/$folder.0
 # remount backup destination as read-only
 
 if [ "$read_only" == "1" ] || [ "$read_only" == "yes" ]; then
-  mount -o remount,ro $mountpoint
+   mount -o remount,ro $mountpoint
 fi
 
 # check partition for errors
 
 if [ "$fscheck" == "1" ] || [ "$fscheck" == "yes" ]; then
-  umount $mountpoint
-  if (($?)); then
-    warning "Could not umount $mountpoint to run fsck"
-  else
-    $nice $fsck -v -y $partition >> $log
-    mount $mountpoint
-  fi
+   umount $mountpoint
+   if (($?)); then
+      warning "Could not umount $mountpoint to run fsck"
+   else
+      $nice $fsck -v -y $partition >> $log
+      mount $mountpoint
+   fi
 fi
 
 # removes the lockfile
 
 if [ ! -z "$lockfile" ]; then
-  $rm $lockfile || warning "Could not remove lockfile $lockfile"
+   $rm $lockfile || warning "Could not remove lockfile $lockfile"
 fi
 
 echo "Finnishing backup at `date`" >> $log
diff --git a/src/ninjareport.in b/src/ninjareport.in
--- a/src/ninjareport.in
+++ b/src/ninjareport.in
@@ -13,7 +13,7 @@
 #  . check for logs that are never updating and warn
 #  . change constantly updating logs (maildir) to be more friendly
 #  . documentation
-#  . maybe make config option that lists all hosts that should report-in, and if 
+#  . maybe make config option that lists all hosts that should report-in, and if
 #    one doesn't then warn
 #  . restrict rsync somehow?
 #  . abstract path for logtail
@@ -29,7 +29,7 @@ process() {
 #
 # note: some backups never finish, such as the maildir one, need to handle these
 # perhaps by looking for FAILED messages?
-# note2: what about logs that aren't being updated? this is a failure case and 
+# note2: what about logs that aren't being updated? this is a failure case and
 # should be looked for
 # note3: there are also these entries:
 # Jan 20 14:00:01 Fatal: No backup actions configured in '/etc/backup.d', run ninjahelper!
@@ -38,27 +38,27 @@ process() {
 logupdates=`maketemp ninjadata`
 
 /usr/sbin/logtail -f $host > $logupdates
-grep FINISHED $logupdates | 
+grep FINISHED $logupdates |
 (
-	fatal=0
-	warning=0
-	error=0
+   fatal=0
+   warning=0
+   error=0
 
-	while read line
-	do
-		line_array=($line)
-		fatal=$(($fatal + ${line_array[8]}))
-		error=$(($error + ${line_array[10]}))
-		warning=$(($warning + ${line_array[12]}))
-	done
-	if (( $fatal || $warning || $error )); then
-		echo "`basename $host .log`: $fatal fatals found, $error errors found, $warning warnings found" >> $statusfile
-		echo "" >> $reportappend
-		echo "`basename $host .log` log entries since last ninjareport" >> $reportappend
-		echo "---------" >> $reportappend
-		cat $logupdates >> $reportappend
-		rm $logupdates
-	fi
+   while read line
+   do
+      line_array=($line)
+      fatal=$(($fatal + ${line_array[8]}))
+      error=$(($error + ${line_array[10]}))
+      warning=$(($warning + ${line_array[12]}))
+   done
+   if (( $fatal || $warning || $error )); then
+      echo "`basename $host .log`: $fatal fatals found, $error errors found, $warning warnings found" >> $statusfile
+      echo "" >> $reportappend
+      echo "`basename $host .log` log entries since last ninjareport" >> $reportappend
+      echo "---------" >> $reportappend
+      cat $logupdates >> $reportappend
+      rm $logupdates
+   fi
 )
 
 }
@@ -69,31 +69,31 @@ reportfile=`maketemp ninjareport`
 
 # Generate a report, only if there are failures
 if [ -s $statusfile ]; then
-	echo "         backupninja mission failures - `date`" >> $reportfile
-	echo "       --------------------------------------------------------------" >> $reportfile
-	echo "" >> $reportfile
-	cat $statusfile | column -t >> $reportfile
-	echo "" >> $reportfile
-	echo "         log entries from failed reports" >> $reportfile
-	echo "       -----------------------------------" >> $reportfile
-	cat $reportappend >> $reportfile
+   echo "         backupninja mission failures - `date`" >> $reportfile
+   echo "       --------------------------------------------------------------" >> $reportfile
+   echo "" >> $reportfile
+   cat $statusfile | column -t >> $reportfile
+   echo "" >> $reportfile
+   echo "         log entries from failed reports" >> $reportfile
+   echo "       -----------------------------------" >> $reportfile
+   cat $reportappend >> $reportfile
 fi
 
 }
 
 usage() {
-	cat << EOF
+   cat << EOF
 This script generates a backupninja status report for all configured
 systems. It requires that each status report is placed in a spot where
 ninjareport can read it, reports are mailed to the reportemail
 configured in @CFGDIR@/backupninja.conf.
 
 The following options are available:
--h, --help		This usage message
--f, --conffile FILE	Use FILE for the configuration instead
-			of @CFGDIR@/backupninja.conf
--m, --mail <email>	Mail the report to this address
--o, --out 		Don't mail the report, just display it
+-h, --help             This usage message
+-f, --conffile FILE    Use FILE for the configuration instead
+                       of @CFGDIR@/backupninja.conf
+-m, --mail <email>     Mail the report to this address
+-o, --out              Don't mail the report, just display it
 
 EOF
 }
@@ -106,45 +106,45 @@ conffile="@CFGDIR@/backupninja.conf"
 ## process command line options
 
 while [ $# -ge 1 ]; do
-	case $1 in
-		-h|--help) 
-                        usage
-			exit 0
-			;;
-		-f|--conffile)
-			if [ -f $2 ]; then
-				conffile=$2
-			else
-				echo "-f|--conffile option must be followed by an existing filename"
-				fatal "-f|--conffile option must be followed by an existing filename"
-				usage
-			fi
-			# we shift here to avoid processing the file path 
-			shift
-			;;
-		-m|--mail)
-			reportemail=$2
-			shift
-			;;
-		-o|--out)
-			mail=0
-			display=1
-			;;
-		*)
-			echo "Unknown option $1"
-			usage
-			exit
-			;;
-	esac
-	shift
-done																										
+   case $1 in
+      -h|--help)
+         usage
+         exit 0
+         ;;
+      -f|--conffile)
+         if [ -f $2 ]; then
+            conffile=$2
+         else
+            echo "-f|--conffile option must be followed by an existing filename"
+            fatal "-f|--conffile option must be followed by an existing filename"
+            usage
+         fi
+         # we shift here to avoid processing the file path
+         shift
+         ;;
+      -m|--mail)
+         reportemail=$2
+         shift
+         ;;
+      -o|--out)
+         mail=0
+         display=1
+         ;;
+      *)
+         echo "Unknown option $1"
+         usage
+         exit
+         ;;
+   esac
+   shift
+done
 
 ## Load and confirm basic configuration values
 
 # bootstrap
 if [ ! -r "$conffile" ]; then
-	echo "Configuration file $conffile not found." 
-	fatal "Configuration file $conffile not found."
+   echo "Configuration file $conffile not found."
+   fatal "Configuration file $conffile not found."
 fi
 
 # find $libdirectory
@@ -153,12 +153,12 @@ if [ -z "$libdirectory" ]; then
    if [ -d "@libdir@" ]; then
       libdirectory="@libdir@"
    else
-      echo "Could not find entry 'libdirectory' in $conffile." 
+      echo "Could not find entry 'libdirectory' in $conffile."
       exit 1
    fi
 else
    if [ ! -d "$libdirectory" ]; then
-      echo "Lib directory $libdirectory not found." 
+      echo "Lib directory $libdirectory not found."
       exit 1
    fi
 fi
@@ -176,17 +176,17 @@ getconf reportemail
 hosts=`find $reportdirectory -follow -mindepth 1 -maxdepth 1 -type f ! -name '*.offset' | sort -n`
 
 if [ -z "$hosts" ]; then
-	echo "Fatal: No backupninja reports found in '$reportdirectory'!"
-	mail=0
+   echo "Fatal: No backupninja reports found in '$reportdirectory'!"
+   mail=0
 fi
 
 statusfile=`maketemp ninjastatus`
 reportappend=`maketemp ninjaappend`
 
 for host in $hosts; do
-	[ -f "$host" ] || continue
-	# Check somehow that the file is a valid report file
-	process $host
+   [ -f "$host" ] || continue
+   # Check somehow that the file is a valid report file
+   process $host
 done
 
 generatereport
@@ -194,12 +194,11 @@ generatereport
 ## mail the report to the report address or display it
 
 if [ -s $reportfile ]; then
-    if [ $mail == 1 ]; then
-	mail -s "backupninja mission failure report" $reportemail < $reportfile
-    fi
+   if [ $mail == 1 ]; then
+      mail -s "backupninja mission failure report" $reportemail < $reportfile
+   fi
 fi
 
 if [ $display == 1 ]; then
-	cat $reportfile
+   cat $reportfile
 fi
-
