Updated the indentation to be according to the agreed standard

diff --git a/handlers/ldap b/handlers/ldap
--- a/handlers/ldap
+++ b/handlers/ldap
@@ -24,66 +24,66 @@ dbsuffixes=(`awk 'BEGIN {OFS=":"} /[:space:]*^database[:space:]*\w*/ {db=$2}; /^
 ## LDIF DUMP
 
 if [ "$ldif" == "yes" ]; then
-	dumpdir="$backupdir"
-	[ -d $dumpdir ] || mkdir -p $dumpdir
-
-	if [ "$databases" == 'all' ]; then
-		dbcount=`grep '^database' $conf | wc -l`
-		let "dbcount = dbcount - 1"
-		databases=`seq 0 $dbcount`;
-	fi	
-	
-	for db in $databases; do
-		if [ `expr index "$dbnum" "="` == "0" ]; then
+   dumpdir="$backupdir"
+   [ -d $dumpdir ] || mkdir -p $dumpdir
+   
+   if [ "$databases" == 'all' ]; then
+      dbcount=`grep '^database' $conf | wc -l`
+      let "dbcount = dbcount - 1"
+      databases=`seq 0 $dbcount`;
+   fi	
+   
+   for db in $databases; do
+      if [ `expr index "$dbnum" "="` == "0" ]; then
 			# db is a number, get the suffix.
-			dbsuffix=${dbsuffixes[$db]/*:/}
-		else
-			dbsuffix=$db
-		fi
+         dbsuffix=${dbsuffixes[$db]/*:/}
+      else
+         dbsuffix=$db
+      fi
 		# some databases don't have suffix (like monitor), skip these
-		if [ "$dbsuffix" == "" ]; then
-			continue;
-		fi
-
-		if [ "$method" == "slapcat" ]; then
-			execstr="$SLAPCAT -f $conf -b $dbsuffix"
-			debug "$execstr"
-		else
-			execstr="$LDAPSEARCH -x -L -b ""$dbsuffix"" -D ""$binddn"" -y $passwordfile"
-			[ -f "$passwordfile" ] || fatal "Password file $passwordfile not found. When method is set to ldapsearch, you must also specify a password file."
-			debug "$execstr"
-		fi
-		if [ ! $test ]; then
-			if [ "$restart" == "yes" ]; then
-				debug "Shutting down ldap server..."
-				/etc/init.d/slapd stop
-			fi
-
-			touch $dumpdir/$dbsuffix.ldif
-			if [ ! -f $dumpdir/$dbsuffix.ldif ]; then
-				fatal "Couldn't create ldif dump file: $dumpdir/$dbsuffix.ldif"
-			fi
-
-			output=`$execstr > $dumpdir/$dbsuffix.ldif`
-			code=$?
-			if [ "$code" == "0" ]; then
-				debug $output
-				info "Successfully finished ldif export of $dbsuffix"
-			else
-				warning $output
-				warning "Failed ldif export of $dbsuffix"
-			fi
-			if [ "$compress" == "yes" ]; then
-				output=`$GZIP -f "$dumpdir/$dbsuffix.ldif" 2>&1`
-				debug $output
-			fi
-
-			if [ "$restart" == "yes" ]; then
-				debug "Starting ldap server..."
-				/etc/init.d/slapd start
-			fi
-		fi
-	done	
+      if [ "$dbsuffix" == "" ]; then
+         continue;
+      fi
+      
+      if [ "$method" == "slapcat" ]; then
+         execstr="$SLAPCAT -f $conf -b $dbsuffix"
+         debug "$execstr"
+      else
+         execstr="$LDAPSEARCH -x -L -b ""$dbsuffix"" -D ""$binddn"" -y $passwordfile"
+         [ -f "$passwordfile" ] || fatal "Password file $passwordfile not found. When method is set to ldapsearch, you must also specify a password file."
+         debug "$execstr"
+      fi
+      if [ ! $test ]; then
+         if [ "$restart" == "yes" ]; then
+            debug "Shutting down ldap server..."
+            /etc/init.d/slapd stop
+         fi
+         
+         touch $dumpdir/$dbsuffix.ldif
+         if [ ! -f $dumpdir/$dbsuffix.ldif ]; then
+            fatal "Couldn't create ldif dump file: $dumpdir/$dbsuffix.ldif"
+         fi
+         
+         output=`$execstr > $dumpdir/$dbsuffix.ldif`
+         code=$?
+         if [ "$code" == "0" ]; then
+            debug $output
+            info "Successfully finished ldif export of $dbsuffix"
+         else
+            warning $output
+            warning "Failed ldif export of $dbsuffix"
+         fi
+         if [ "$compress" == "yes" ]; then
+            output=`$GZIP -f "$dumpdir/$dbsuffix.ldif" 2>&1`
+            debug $output
+         fi
+         
+         if [ "$restart" == "yes" ]; then
+            debug "Starting ldap server..."
+            /etc/init.d/slapd start
+         fi
+      fi
+   done	
 fi
 
 return 0
