Refactor: place remote dir verification/creation in library
We'll need to use this code with bup too, so we should be able to reuse
it.

diff --git a/lib/ssh.in b/lib/ssh.in
--- a/lib/ssh.in
+++ b/lib/ssh.in
@@ -47,3 +47,42 @@ function ssh_create_root_key() {
    return 0
 }
 
+function ssh_ensure_remote_dir() {
+   local title=$1
+   local directory=$2
+   local host=$3
+   local user=$4
+
+   local remote_status="ok"
+
+   echo "Testing to see if remote backup directory exists and is writable"
+   ssh $user@$host "test -d ${directory}"
+   if [ $? = 0 ]; then
+      ssh $user@$host "test -w $directory"
+      if [ $? != 0 ]; then
+         msgBox "destination directory is not writable!" "The remote destination directory is not writable by the user you specified. Please fix the permissions on the directory and then try again."
+         remote_status=failed
+      fi
+   else
+      booleanBox "Remote directory does not exist" "The destination backup directory does not exist, do you want me to create it for you?"
+      if [ $? = 0 ]; then
+         ssh $user@$host "mkdir -p ${directory}"
+         result=$?
+         case $result in
+            0) msgBox "$title: success" "Creation of the remote destination directory was a success!";;
+            1) msgBox "$title: error" "Connected successfully to $user@$host, but was unable to create the destination directory, check the directory permissions."
+               remote_status=failed;;
+            255) msgBox "$title: error" "Failed to connect to $user@$host. Check hostname, username, and password. Also, make sure sshd is running on the destination host."
+               remote_status=failed;;
+            *) msgBox "$title: error" "Unexpected error."
+               remote_status=failed;;
+         esac
+      fi
+   fi
+
+   if [ "$remote_status" != "ok" ]; then
+      return 1
+   fi
+
+   return 0
+}
